module.exports = {
  version: 2,
  storybook: {
    exclude: [
      'Components/Avatar: Default',
      'Components/Badge: Default',
      'Components/Badge: Count',
      'Components/Badge: Examples',
      'Components/Breadcrumbs: Default',
      'Components/Breadcrumbs: Breadcrumb Item',
      'Components/Button: Default',
      'Components/Checkbox: Default',
      'Components/Checkbox Group: Default',
      'Components/Chip: Default',
      'Components/Combobox: Empty',
      'Components/Datepicker',
      'Components/Dropdown: Default',
      'Components/Emoji: Default',
      'Components/Emoji: Custom Emoji',
      'Components/Emoji Text Wrapper: Default',
      'Components/Icon: Default',
      'Components/Image Viewer: Default',
      'Components/Input Group: Default',
      'Components/Keyboard Shortcut: Default',
      'Components/Link: Default',
      'Components/Pagination: Default',
      'Components/Popover: Default',
      'Components/Presence: Default',
      'Components/Radio: Default',
      'Components/Radio Group: Default',
      'Components/Rich Text Editor',
      'Components/Root Layout',
      'Components/Scroller: Dynamic',
      'Components/Select Menu: Default',
      'Components/Skeleton: Default',
      'Components/Tabs: Tab',
      'Components/Tabs: Tab Panel',
      'Components/Tabs: Default',
      'Components/Toggle: Default',
      'Components/Tooltip: Default',
      'Components/Tooltip: Flip',
      'Components/Tooltip: Change On Click',
      'Components/Validation Messages: Default',
      'Recipes/Buttons/Callbar Button: Default',
      'Recipes/Buttons/Callbar Button: Callbar',
      'Recipes/Buttons/Callbar Button With Popover: Default',
      'Recipes/Comboboxes/Combobox Multi-Select: With Max Validation',
      'Recipes/Comboboxes/Combobox With Popover: Empty',
      'Recipes/Conversation View/Feed Item Row: Default',
      'Recipes/Conversation View/Feed Item Pill: Default',
      'Recipes/Leftbar/Callbox: Default',
      'Recipes/Leftbar/Contact Row: Default',
      'Recipes/Leftbar/General Row: Default',
      'Recipes/Leftbar/Group Row: Default',
      'Recipes/Leftbar/Unread Pill: Default',
      'Recipes/List Items/Contact Info: Default',
      'Recipes/Notices/Top Banner Info: Default',
      'Utilities/Lazy Show',
      'Visual Testing/',
    ],
  },
  snapshot: {
    enableJavaScript: true,
    widths: [1280],
  },
  discovery: {
    disableCache: true,
    allowedHostnames: [
      'proxyme.percy.io',
      'render.percy.local',
    ],
    networkIdleTimeout: 150,
    concurrency: 1,
  },
};
