packages:
  # documentation sites
  - 'apps/*'
  # npm publishable packages
  - 'packages/*'
  - 'packages/dialtone-icons/*'
  - 'packages/language-server/*'
  # yeoman generator
  - 'generator-dialtone'
