# Dialtone
DIALTONE_CLOSE_BUTTON = 클릭하여 닫기
DIALTONE_BREADCRUMBS_ARIA_LABEL = 탐색 경로
DIALTONE_LOADING = 불러오는 중
DIALTONE_UNREAD_MESSAGE_COUNT_TEXT =
    { $unreadCount ->
        [0] 읽지 않은 메시지 없음
        [1] 읽지 않은 메시지 1개
       *[other] 읽지 않은 메시지 { $unreadCount }개
    }
DIALTONE_UNREAD_MENTION_COUNT_TEXT =
    { $unreadCount ->
        [0] 읽지 않은 멘션 없음
        [1] 읽지 않은 멘션 1개
       *[other] 읽지 않은 멘션 { $unreadCount }개
    }
DIALTONE_TYPING_TEXT = 입력 중
DIALTONE_ATTACHMENT_CAROUSEL_CLICK_TO_OPEN_ARIA_LABEL = 클릭하여 열기
DIALTONE_ATTACHMENT_CAROUSEL_PROGRESS_BAR_ARIA_LABEL = 업로드 중
DIALTONE_ATTACHMENT_CAROUSEL_LEFT_ARROW_ARIA_LABEL = 이전
DIALTONE_ATTACHMENT_CAROUSEL_RIGHT_ARROW_ARIA_LABEL = 다음
DIALTONE_CALLBAR_BUTTON_WITH_DROPDOWN_ARROW_BUTTON_ARIA_LABEL = 드롭다운 열기
DIALTONE_CALLBAR_BUTTON_WITH_POPOVER_ARROW_BUTTON_ARIA_LABEL = 팝오버 열기
DIALTONE_CONTACT_CENTERS_ROW_MENU_BUTTON_LABEL = 메뉴 열기
DIALTONE_DATEPICKER_PREVIOUS_MONTH = 지난달
DIALTONE_DATEPICKER_NEXT_MONTH = 다음 달
DIALTONE_DATEPICKER_PREVIOUS_YEAR = 이전 연도
DIALTONE_DATEPICKER_NEXT_YEAR = 다음 해
DIALTONE_DATEPICKER_SELECT_DAY = 일 선택
DIALTONE_DATEPICKER_CHANGE_TO = 다음으로 변경
DIALTONE_EDITOR_CONFIRM_SET_LINK_BUTTON =
    .title = 확인
    .aria-label = 설정된 링크 확인
DIALTONE_EDITOR_REMOVE_LINK_BUTTON =
    .title = 제거
    .aria-label = 링크 제거
DIALTONE_EDITOR_CANCEL_SET_LINK_BUTTON =
    .title = 취소
    .aria-label = 설정된 링크 취소
DIALTONE_EDITOR_QUICK_REPLY_BUTTON_LABEL = 템플릿
DIALTONE_EDITOR_BOLD_BUTTON_LABEL = 굵게
DIALTONE_EDITOR_ITALICS_BUTTON_LABEL = 이탤릭체
DIALTONE_EDITOR_UNDERLINE_BUTTON_LABEL = 밑줄
DIALTONE_EDITOR_STRIKE_BUTTON_LABEL = 취소선
DIALTONE_EDITOR_ALIGN_LEFT_BUTTON_LABEL = 왼쪽 정렬
DIALTONE_EDITOR_ALIGN_CENTER_BUTTON_LABEL = 가운데 정렬
DIALTONE_EDITOR_ALIGN_RIGHT_BUTTON_LABEL = 오른쪽 정렬
DIALTONE_EDITOR_ALIGN_JUSTIFY_BUTTON_LABEL = 양쪽 정렬
DIALTONE_EDITOR_BULLET_LIST_BUTTON_LABEL = 글머리 기호 목록
DIALTONE_EDITOR_ORDERED_LIST_BUTTON_LABEL = 순서가 있는 목록
DIALTONE_EDITOR_QUOTE_BUTTON_LABEL = 인용
DIALTONE_EDITOR_CODE_BUTTON_LABEL = 코드
DIALTONE_EDITOR_IMAGE_BUTTON_LABEL = 이미지
DIALTONE_EDITOR_LINK_BUTTON_LABEL = 링크
DIALTONE_EDITOR_ADD_LINK_BUTTON =
    .title = 링크 추가
    .aria-label = 링크를 추가할 입력 필드
DIALTONE_EDITOR_FONT_STYLE_BUTTON_LABEL = 글꼴
DIALTONE_EDITOR_FONT_STYLE_SEARCH_PLACEHOLDER = 글꼴 검색
DIALTONE_EDITOR_FONT_SIZE_BUTTON_LABEL = 글꼴 크기
DIALTONE_EDITOR_FONT_COLOR_BUTTON_LABEL = 텍스트 색상
DIALTONE_EMOJI_ROW_REACTION_LABEL =
    { $personCount ->
       *[other] { $reaction }(으)로 반응함
    }
DIALTONE_EMOJI_PICKER_ADD_EMOJI_LABEL = 이모지 추가
DIALTONE_EMOJI_PICKER_SEARCH_NO_RESULTS_LABEL = 결과 없음
DIALTONE_EMOJI_PICKER_SEARCH_RESULTS_LABEL = 검색 결과
DIALTONE_EMOJI_PICKER_SEARCH_PLACEHOLDER_LABEL = 검색...
DIALTONE_EMOJI_PICKER_SKIN_SELECTOR_BUTTON_TOOLTIP_LABEL = 기본 피부색 변경
DIALTONE_EMOJI_PICKER_TABSET_RECENTLY_USED_LABEL = 가장 최근 사용
DIALTONE_EMOJI_PICKER_TABSET_SMILEYS_AND_PEOPLE_LABEL = 스마일 및 사람
DIALTONE_EMOJI_PICKER_TABSET_NATURE_LABEL = 자연
DIALTONE_EMOJI_PICKER_TABSET_FOOD_LABEL = 음식
DIALTONE_EMOJI_PICKER_TABSET_ACTIVITY_LABEL = 활동
DIALTONE_EMOJI_PICKER_TABSET_TRAVEL_LABEL = 여행
DIALTONE_EMOJI_PICKER_TABSET_OBJECTS_LABEL = 개체
DIALTONE_EMOJI_PICKER_TABSET_SYMBOLS_LABEL = 기호
DIALTONE_EMOJI_PICKER_TABSET_FLAGS_LABEL = 깃발
DIALTONE_EMOJI_PICKER_TABSET_CUSTOM_LABEL = 맞춤
DIALTONE_FEED_ITEM_PILL_ARIA_LABEL = 클릭하여 확장
DIALTONE_GENERAL_ROW_ACTIVE_VOICE_CHAT_TEXT = 활성 음성 채팅
DIALTONE_GENERAL_ROW_CALL_BUTTON_TOOLTIP = 통화
DIALTONE_GENERAL_ROW_DND_TEXT_TOOLTIP = 방해 금지
DIALTONE_GROUP_ROW_GROUP_COUNT_TEXT =
    { $count ->
        [1] 사용자 1명
       *[other] 사용자 { $count }명
    }
DIALTONE_IVR_NODE_MENU_BUTTON_ARIA_LABEL = 메뉴 열기
DIALTONE_IVR_NODE_PROMPTMENU_ARIA_LABEL = 프롬프트 메뉴 노드
DIALTONE_IVR_NODE_PROMPTCOLLECT_ARIA_LABEL = 프롬프트 수집 노드
DIALTONE_IVR_NODE_PROMPTPLAY_ARIA_LABEL = 프롬프트 재생 노드
DIALTONE_IVR_NODE_GOTOEXPERT_ARIA_LABEL = 전문가 노드로 이동
DIALTONE_IVR_NODE_BRANCH_ARIA_LABEL = 분기 노드
DIALTONE_IVR_NODE_GOTO_ARIA_LABEL = 노드로 이동
DIALTONE_IVR_NODE_ASSIGN_ARIA_LABEL = 노드 할당
DIALTONE_IVR_NODE_CUSTOMERDATA_ARIA_LABEL = 고객 데이터 노드
DIALTONE_IVR_NODE_TRANSFER_ARIA_LABEL = 전송 노드
DIALTONE_IVR_NODE_HANGUP_ARIA_LABEL = 전화 끊기 노드
DIALTONE_MESSAGE_INPUT_SEND_BUTTON_ARIA_LABEL = 전송
DIALTONE_MESSAGE_INPUT_IMAGE_PICKER_BUTTON_ARIA_LABEL = 이미지 첨부
DIALTONE_MESSAGE_INPUT_EMOJI_PICKER_BUTTON_ARIA_LABEL = 이모지 선택
DIALTONE_MESSAGE_INPUT_CANCEL_BUTTON_ARIA_LABEL = 취소
DIALTONE_MESSAGE_INPUT_BOLD_BUTTON_LABEL =
    .aria-label = 선택된 텍스트에 굵게 효과 적용
    .tooltip-text = 굵게
DIALTONE_MESSAGE_INPUT_ITALIC_BUTTON_LABEL =
    .aria-label = 선택한 텍스트에 기울임꼴 적용
    .tooltip-text = 기울임꼴
DIALTONE_MESSAGE_INPUT_STRIKETHROUGH_BUTTON_LABEL =
    .aria-label = 선택한 텍스트에 취소선 적용
    .tooltip-text = 취소선
DIALTONE_MESSAGE_INPUT_BULLET_LIST_BUTTON_LABEL =
    .aria-label = 선택한 텍스트에서 글머리 기호 목록 생성 또는 편집
    .tooltip-text = 글머리 기호 목록
DIALTONE_MESSAGE_INPUT_ORDERED_LIST_BUTTON_LABEL =
    .aria-label = 선택한 텍스트에서 순서가 있는 목록 생성 또는 편집
    .tooltip-text = 순서가 있는 목록
DIALTONE_MESSAGE_INPUT_BLOCK_QUOTE_BUTTON_LABEL =
    .aria-label = 선택한 텍스트에서 블록 인용 생성 또는 편집
    .tooltip-text = 블록 인용
DIALTONE_MESSAGE_INPUT_CODE_BUTTON_LABEL =
    .aria-label = 선택된 텍스트에서 코드 생성 또는 편집
    .tooltip-text = 코드
DIALTONE_MESSAGE_INPUT_CODE_BLOCK_BUTTON_LABEL =
    .aria-label = 선택된 텍스트에서 코드 블록 생성 또는 편집
    .tooltip-text = 코드 블록
DIALTONE_MESSAGE_INPUT_LINK_BUTTON_LABEL =
    .aria-label = 선택된 텍스트에서 링크 생성 또는 편집
    .tooltip-text = 링크
DIALTONE_MESSAGE_INPUT_LINK_DIALOG_TITLE = 링크 추가
DIALTONE_MESSAGE_INPUT_LINK_TEXT_LABEL = 표시할 텍스트(선택 사항)
DIALTONE_MESSAGE_INPUT_LINK_LINK_LABEL = 링크
DIALTONE_MESSAGE_INPUT_LINK_LINK_PLACEHOLDER = 예: https://www.dialpad.com
DIALTONE_MESSAGE_INPUT_LINK_REMOVE_LABEL = 제거
DIALTONE_MESSAGE_INPUT_LINK_CANCEL_LABEL = 취소
DIALTONE_MESSAGE_INPUT_LINK_CONFIRM_LABEL = 완료
DIALTONE_EDITOR_VARIABLE_BUTTON_LABEL = 변수
DIALTONE_EDITOR_VARIABLE_LABEL = 대체 텍스트
DIALTONE_EDITOR_VARIABLE_VALIDATE_DESCRIPTION = 변수 데이터를 사용할 수 없을 때 사용됩니다.
DIALTONE_EDITOR_VARIABLE_VALIDATE_MESSAGE = 최대 100자가 허용됩니다.
DIALTONE_EDITOR_VARIABLE_POPOVER_SEARCH_PLACEHOLDER = 검색 변수
DIALTONE_PAGINATION_FIRST_PAGE = 첫 페이지
DIALTONE_PAGINATION_PREVIOUS_PAGE = 이전 페이지
DIALTONE_PAGINATION_NEXT_PAGE = 다음 페이지
DIALTONE_PAGINATION_LAST_PAGE = 마지막 페이지
DIALTONE_PAGINATION_PAGE_NUMBER = 페이지 번호: { $page }
DIALTONE_RICH_TEXT_EDITOR_EDIT_BUTTON_LABEL = 편집
DIALTONE_RICH_TEXT_EDITOR_OPEN_LINK_BUTTON_LABEL = 링크 열기
DIALTONE_RICH_TEXT_EDITOR_REMOVE_BUTTON_LABEL = 제거
DIALTONE_SETTINGS_MENU_DEFAULT_BUTTON_LABEL = 설정
DIALTONE_SETTINGS_MENU_UPDATE_BUTTON_LABEL = 업데이트
DIALTONE_UNREAD_PILL_MENTIONS_TEXT = 읽지 않은 멘션
DIALTONE_UNREAD_PILL_MESSAGES_TEXT = 읽지 않은 메시지
# Storybook only
STORYBOOK_LANGUAGE_ENGLISH = 영어
STORYBOOK_LANGUAGE_CHINESE = 중국어
STORYBOOK_LANGUAGE_DUTCH = 네덜란드어
STORYBOOK_LANGUAGE_FRENCH = 프랑스어
STORYBOOK_LANGUAGE_GERMAN = 독일어
STORYBOOK_LANGUAGE_ITALIAN = 이탈리아어
STORYBOOK_LANGUAGE_JAPANESE = 일본어
STORYBOOK_LANGUAGE_KOREAN = 한국어
STORYBOOK_LANGUAGE_PORTUGUESE = 포르투갈어
STORYBOOK_LANGUAGE_RUSSIAN = 러시아어
STORYBOOK_LANGUAGE_SPANISH = 스페인어
STORYBOOK_LANGUAGE_SWEDISH = 스웨덴어
STORYBOOK_SET_LANGUAGE = 언어 설정
STORYBOOK_YOU = 나
STORYBOOK_REACTION_NAMES_2 = Olivia Chen, Benjamin Carter, Sophia Rodriguez, William Kim, Isabella Garcia
STORYBOOK_REACTION_NAMES_3 = Olivia Chen, { STORYBOOK_YOU }
