# Dialtone
DIALTONE_CLOSE_BUTTON = Klicka för att stänga
DIALTONE_BREADCRUMBS_ARIA_LABEL = länkstigar
DIALTONE_LOADING = laddar
DIALTONE_UNREAD_MESSAGE_COUNT_TEXT =
    { $unreadCount ->
        [0] Inga olästa meddelanden
        [1] 1 oläst meddelande
       *[other] { $unreadCount } olästa meddelanden
    }
DIALTONE_UNREAD_MENTION_COUNT_TEXT =
    { $unreadCount ->
        [0] Inga olästa omnämnanden
        [1] 1 oläst omnämnande
       *[other] { $unreadCount } olästa omnämnanden
    }
DIALTONE_TYPING_TEXT = Skriver
DIALTONE_ATTACHMENT_CAROUSEL_CLICK_TO_OPEN_ARIA_LABEL = Klicka för att öppna
DIALTONE_ATTACHMENT_CAROUSEL_PROGRESS_BAR_ARIA_LABEL = Laddar upp
DIALTONE_ATTACHMENT_CAROUSEL_LEFT_ARROW_ARIA_LABEL = Tidigare
DIALTONE_ATTACHMENT_CAROUSEL_RIGHT_ARROW_ARIA_LABEL = Nästa
DIALTONE_CALLBAR_BUTTON_WITH_DROPDOWN_ARROW_BUTTON_ARIA_LABEL = Öppna rullgardinsmeny
DIALTONE_CALLBAR_BUTTON_WITH_POPOVER_ARROW_BUTTON_ARIA_LABEL = Öppna snabbfönster
DIALTONE_CONTACT_CENTERS_ROW_MENU_BUTTON_LABEL = Öppna meny
DIALTONE_DATEPICKER_PREVIOUS_MONTH = Föregående månad
DIALTONE_DATEPICKER_NEXT_MONTH = Nästa månad
DIALTONE_DATEPICKER_PREVIOUS_YEAR = Tidigare år
DIALTONE_DATEPICKER_NEXT_YEAR = Nästa år
DIALTONE_DATEPICKER_SELECT_DAY = Välj dag
DIALTONE_DATEPICKER_CHANGE_TO = Ändra till
DIALTONE_EDITOR_CONFIRM_SET_LINK_BUTTON =
    .title = Bekräfta
    .aria-label = Bekräfta inställd länk
DIALTONE_EDITOR_REMOVE_LINK_BUTTON =
    .title = Ta bort
    .aria-label = Ta bort länk
DIALTONE_EDITOR_CANCEL_SET_LINK_BUTTON =
    .title = Stäng
    .aria-label = Avbryt inställd länk
DIALTONE_EDITOR_QUICK_REPLY_BUTTON_LABEL = Mall
DIALTONE_EDITOR_BOLD_BUTTON_LABEL = Fetstil
DIALTONE_EDITOR_ITALICS_BUTTON_LABEL = Kursiv stil
DIALTONE_EDITOR_UNDERLINE_BUTTON_LABEL = Understrykning
DIALTONE_EDITOR_STRIKE_BUTTON_LABEL = Genomstrykning
DIALTONE_EDITOR_ALIGN_LEFT_BUTTON_LABEL = Justera vänster
DIALTONE_EDITOR_ALIGN_CENTER_BUTTON_LABEL = Centrera
DIALTONE_EDITOR_ALIGN_RIGHT_BUTTON_LABEL = Högerjustera
DIALTONE_EDITOR_ALIGN_JUSTIFY_BUTTON_LABEL = Marginaljusterad
DIALTONE_EDITOR_BULLET_LIST_BUTTON_LABEL = Punktlista
DIALTONE_EDITOR_ORDERED_LIST_BUTTON_LABEL = Numrerad lista
DIALTONE_EDITOR_QUOTE_BUTTON_LABEL = Citat
DIALTONE_EDITOR_CODE_BUTTON_LABEL = Kod
DIALTONE_EDITOR_IMAGE_BUTTON_LABEL = Bild
DIALTONE_EDITOR_LINK_BUTTON_LABEL = Länk
DIALTONE_EDITOR_ADD_LINK_BUTTON =
    .title = Lägg till länk
    .aria-label = Inmatningsfält för att lägga till länk
DIALTONE_EDITOR_FONT_STYLE_BUTTON_LABEL = Typsnitt
DIALTONE_EDITOR_FONT_STYLE_SEARCH_PLACEHOLDER = Sök typsnitt
DIALTONE_EDITOR_FONT_SIZE_BUTTON_LABEL = Teckenstorlek
DIALTONE_EDITOR_FONT_COLOR_BUTTON_LABEL = Textfärg
DIALTONE_EMOJI_ROW_REACTION_LABEL =
    { $personCount ->
        [one] reagerade med { $reaction }
       *[other] reagerade med { $reaction }
    }
DIALTONE_EMOJI_PICKER_ADD_EMOJI_LABEL = Lägg till emoji
DIALTONE_EMOJI_PICKER_SEARCH_NO_RESULTS_LABEL = Inga resultat
DIALTONE_EMOJI_PICKER_SEARCH_RESULTS_LABEL = Sökresultat
DIALTONE_EMOJI_PICKER_SEARCH_PLACEHOLDER_LABEL = Sök …
DIALTONE_EMOJI_PICKER_SKIN_SELECTOR_BUTTON_TOOLTIP_LABEL = Ändra standardhudton
DIALTONE_EMOJI_PICKER_TABSET_RECENTLY_USED_LABEL = Senast använda
DIALTONE_EMOJI_PICKER_TABSET_SMILEYS_AND_PEOPLE_LABEL = Smileys och personer
DIALTONE_EMOJI_PICKER_TABSET_NATURE_LABEL = Natur
DIALTONE_EMOJI_PICKER_TABSET_FOOD_LABEL = Mat
DIALTONE_EMOJI_PICKER_TABSET_ACTIVITY_LABEL = Aktivitet
DIALTONE_EMOJI_PICKER_TABSET_TRAVEL_LABEL = resor
DIALTONE_EMOJI_PICKER_TABSET_OBJECTS_LABEL = Objekt
DIALTONE_EMOJI_PICKER_TABSET_SYMBOLS_LABEL = Symboler
DIALTONE_EMOJI_PICKER_TABSET_FLAGS_LABEL = Markeringar
DIALTONE_EMOJI_PICKER_TABSET_CUSTOM_LABEL = Anpassad
DIALTONE_FEED_ITEM_PILL_ARIA_LABEL = Klicka för att expandera
DIALTONE_GENERAL_ROW_ACTIVE_VOICE_CHAT_TEXT = Aktiv röstchatt
DIALTONE_GENERAL_ROW_CALL_BUTTON_TOOLTIP = Ring
DIALTONE_GENERAL_ROW_DND_TEXT_TOOLTIP = Stör ej
DIALTONE_GROUP_ROW_GROUP_COUNT_TEXT =
    { $count ->
        [1] 1 användare
       *[other] { $count }-användare
    }
DIALTONE_IVR_NODE_MENU_BUTTON_ARIA_LABEL = Öppna meny
DIALTONE_IVR_NODE_PROMPTMENU_ARIA_LABEL = promptmenynod
DIALTONE_IVR_NODE_PROMPTCOLLECT_ARIA_LABEL = promptinsamlingsnod
DIALTONE_IVR_NODE_PROMPTPLAY_ARIA_LABEL = promptuppspelningsnod
DIALTONE_IVR_NODE_GOTOEXPERT_ARIA_LABEL = gå till expertnod
DIALTONE_IVR_NODE_BRANCH_ARIA_LABEL = förgreningsnod
DIALTONE_IVR_NODE_GOTO_ARIA_LABEL = gå till nod
DIALTONE_IVR_NODE_ASSIGN_ARIA_LABEL = tilldela nod
DIALTONE_IVR_NODE_CUSTOMERDATA_ARIA_LABEL = kunddatanod
DIALTONE_IVR_NODE_TRANSFER_ARIA_LABEL = överföringsnod
DIALTONE_IVR_NODE_HANGUP_ARIA_LABEL = påläggningsnod
DIALTONE_MESSAGE_INPUT_SEND_BUTTON_ARIA_LABEL = Skicka
DIALTONE_MESSAGE_INPUT_IMAGE_PICKER_BUTTON_ARIA_LABEL = Bifoga bild
DIALTONE_MESSAGE_INPUT_EMOJI_PICKER_BUTTON_ARIA_LABEL = Välj emoji
DIALTONE_MESSAGE_INPUT_CANCEL_BUTTON_ARIA_LABEL = Stäng
DIALTONE_MESSAGE_INPUT_BOLD_BUTTON_LABEL =
    .aria-label = Växla fetstil på markerad text
    .tooltip-text = Fetstil
DIALTONE_MESSAGE_INPUT_ITALIC_BUTTON_LABEL =
    .aria-label = Växla kursiv stil på markerad text
    .tooltip-text = Kursiv
DIALTONE_MESSAGE_INPUT_STRIKETHROUGH_BUTTON_LABEL =
    .aria-label = Växla genomstrykning på markerad text
    .tooltip-text = Genomstrykning
DIALTONE_MESSAGE_INPUT_BULLET_LIST_BUTTON_LABEL =
    .aria-label = Skapa eller redigera punktlista på markerad text
    .tooltip-text = Punktlista
DIALTONE_MESSAGE_INPUT_ORDERED_LIST_BUTTON_LABEL =
    .aria-label = Skapa eller redigera numrerad lista på markerad text
    .tooltip-text = Numrerad lista
DIALTONE_MESSAGE_INPUT_BLOCK_QUOTE_BUTTON_LABEL =
    .aria-label = Skapa eller redigera blockcitat på markerad text
    .tooltip-text = Blockcitat
DIALTONE_MESSAGE_INPUT_CODE_BUTTON_LABEL =
    .aria-label = Skapa eller redigera kod på markerad text
    .tooltip-text = Kod
DIALTONE_MESSAGE_INPUT_CODE_BLOCK_BUTTON_LABEL =
    .aria-label = Skapa eller redigera kodblock på markerad text
    .tooltip-text = Kodblock
DIALTONE_MESSAGE_INPUT_LINK_BUTTON_LABEL =
    .aria-label = Skapa eller redigera länk på markerad text
    .tooltip-text = Länk
DIALTONE_MESSAGE_INPUT_LINK_DIALOG_TITLE = Lägg till en länk
DIALTONE_MESSAGE_INPUT_LINK_TEXT_LABEL = Text att visa (valfritt)
DIALTONE_MESSAGE_INPUT_LINK_LINK_LABEL = Länk
DIALTONE_MESSAGE_INPUT_LINK_LINK_PLACEHOLDER = t.ex. https://www.dialpad.com
DIALTONE_MESSAGE_INPUT_LINK_REMOVE_LABEL = Ta bort
DIALTONE_MESSAGE_INPUT_LINK_CANCEL_LABEL = Stäng
DIALTONE_MESSAGE_INPUT_LINK_CONFIRM_LABEL = Klart
DIALTONE_EDITOR_VARIABLE_BUTTON_LABEL = Variabel
DIALTONE_EDITOR_VARIABLE_LABEL = Alternativ text
DIALTONE_EDITOR_VARIABLE_VALIDATE_DESCRIPTION = Används när variabeldata inte är tillgängliga.
DIALTONE_EDITOR_VARIABLE_VALIDATE_MESSAGE = Maximalt 100 tecken tillåts.
DIALTONE_EDITOR_VARIABLE_POPOVER_SEARCH_PLACEHOLDER = Sök variabel
DIALTONE_PAGINATION_FIRST_PAGE = Första sida
DIALTONE_PAGINATION_PREVIOUS_PAGE = Föregående sida
DIALTONE_PAGINATION_NEXT_PAGE = Nästa sida
DIALTONE_PAGINATION_LAST_PAGE = Senaste sida
DIALTONE_PAGINATION_PAGE_NUMBER = Sidanummer { $page }
DIALTONE_RICH_TEXT_EDITOR_EDIT_BUTTON_LABEL = Redigera
DIALTONE_RICH_TEXT_EDITOR_OPEN_LINK_BUTTON_LABEL = Öppna länk
DIALTONE_RICH_TEXT_EDITOR_REMOVE_BUTTON_LABEL = Ta bort
DIALTONE_SETTINGS_MENU_DEFAULT_BUTTON_LABEL = Inställningar
DIALTONE_SETTINGS_MENU_UPDATE_BUTTON_LABEL = Uppdatera
DIALTONE_UNREAD_PILL_MENTIONS_TEXT = Olästa omnämningar
DIALTONE_UNREAD_PILL_MESSAGES_TEXT = Olästa meddelanden
# Storybook only
STORYBOOK_LANGUAGE_ENGLISH = Engelska
STORYBOOK_LANGUAGE_CHINESE = Kinesiska
STORYBOOK_LANGUAGE_DUTCH = Holländska
STORYBOOK_LANGUAGE_FRENCH = Franska
STORYBOOK_LANGUAGE_GERMAN = Tyska
STORYBOOK_LANGUAGE_ITALIAN = Italienska
STORYBOOK_LANGUAGE_JAPANESE = Japanska
STORYBOOK_LANGUAGE_KOREAN = Koreanska
STORYBOOK_LANGUAGE_PORTUGUESE = Portugisiska
STORYBOOK_LANGUAGE_RUSSIAN = Ryska
STORYBOOK_LANGUAGE_SPANISH = Spanska
STORYBOOK_LANGUAGE_SWEDISH = Svenska
STORYBOOK_SET_LANGUAGE = Ställ in språk
STORYBOOK_YOU = Du
STORYBOOK_REACTION_NAMES_2 = Olivia Chen, Benjamin Carter, Sophia Rodriguez, William Kim och Isabella Garcia
STORYBOOK_REACTION_NAMES_3 = Olivia Chen och { STORYBOOK_YOU }
