name: Setup Environment
description: Common steps  set up the environment for tasks

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - name: Configure GitHub Packages auth
      shell: bash
      run: |
        # Required because i18n & i18n-services are private. Along with .npmrc config.
        echo "@dialpad:registry=https://npm.pkg.github.com" >> ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ github.token }}" >> ~/.npmrc

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
