# Dialtone
DIALTONE_CLOSE_BUTTON = Zum Schließen klicken
DIALTONE_BREADCRUMBS_ARIA_LABEL = Brotkrumen
DIALTONE_LOADING = Lädt ...
DIALTONE_UNREAD_MESSAGE_COUNT_TEXT =
  { $unreadCount ->
  [0] Keine ungelesenen Nachrichten
  [1] 1 ungelesene Nachricht
  *[other] { $unreadCount } ungelesene Nachrichten
      }
DIALTONE_UNREAD_MENTION_COUNT_TEXT =
  { $unreadCount ->
  [0] Keine ungelesenen Erwähnungen
  [1] 1 ungelesene Erwähnung
  *[other] { $unreadCount } ungelesene Erwähnungen
      }
DIALTONE_TYPING_TEXT = schreibt
DIALTONE_ATTACHMENT_CAROUSEL_CLICK_TO_OPEN_ARIA_LABEL = Zum Öffnen klicken
DIALTONE_ATTACHMENT_CAROUSEL_PROGRESS_BAR_ARIA_LABEL = Wird hochgeladen
DIALTONE_ATTACHMENT_CAROUSEL_LEFT_ARROW_ARIA_LABEL = Vorherig
DIALTONE_ATTACHMENT_CAROUSEL_RIGHT_ARROW_ARIA_LABEL = Weiter
DIALTONE_CALLBAR_BUTTON_WITH_DROPDOWN_ARROW_BUTTON_ARIA_LABEL = Dropdown-Menü öffnen
DIALTONE_CALLBAR_BUTTON_WITH_POPOVER_ARROW_BUTTON_ARIA_LABEL = Popover öffnen
DIALTONE_CONTACT_CENTERS_ROW_MENU_BUTTON_LABEL = Menü öffnen
DIALTONE_DATEPICKER_PREVIOUS_MONTH = Vorheriger Monat
DIALTONE_DATEPICKER_NEXT_MONTH = nächsten Monat
DIALTONE_DATEPICKER_PREVIOUS_YEAR = Vorheriges Jahr
DIALTONE_DATEPICKER_NEXT_YEAR = nächstes Jahr
DIALTONE_DATEPICKER_SELECT_DAY = Tag auswählen
DIALTONE_DATEPICKER_CHANGE_TO = Wechseln zu
DIALTONE_EDITOR_CONFIRM_SET_LINK_BUTTON =
  .title = Bestätigen
  .aria-label = Gesetzten Link bestätigen
DIALTONE_EDITOR_REMOVE_LINK_BUTTON =
  .title = Entfernen
  .aria-label = Link entfernen
DIALTONE_EDITOR_CANCEL_SET_LINK_BUTTON =
  .title = ABBRECHEN
  .aria-label = Set-Link abbrechen
DIALTONE_EDITOR_QUICK_REPLY_BUTTON_LABEL = Vorlage
DIALTONE_EDITOR_BOLD_BUTTON_LABEL = Fett
DIALTONE_EDITOR_ITALICS_BUTTON_LABEL = Kursiv
DIALTONE_EDITOR_UNDERLINE_BUTTON_LABEL = Unterstreichen
DIALTONE_EDITOR_STRIKE_BUTTON_LABEL = Durchstreichen
DIALTONE_EDITOR_ALIGN_LEFT_BUTTON_LABEL = Linksbündig ausrichten
DIALTONE_EDITOR_ALIGN_CENTER_BUTTON_LABEL = Zentriert ausrichten
DIALTONE_EDITOR_ALIGN_RIGHT_BUTTON_LABEL = Rechtsbündig ausrichten
DIALTONE_EDITOR_ALIGN_JUSTIFY_BUTTON_LABEL = Blocksatz ausrichten
DIALTONE_EDITOR_BULLET_LIST_BUTTON_LABEL = Aufzählung
DIALTONE_EDITOR_ORDERED_LIST_BUTTON_LABEL = Geordnete Liste
DIALTONE_EDITOR_QUOTE_BUTTON_LABEL = Zitieren
DIALTONE_EDITOR_CODE_BUTTON_LABEL = Code
DIALTONE_EDITOR_IMAGE_BUTTON_LABEL = Bild
DIALTONE_EDITOR_LINK_BUTTON_LABEL = Link
DIALTONE_EDITOR_ADD_LINK_BUTTON =
  .title = Link hinzufügen
  .aria-label = Eingabefeld zum Hinzufügen eines Links
DIALTONE_EMOJI_ROW_REACTION_LABEL =
  { $personCount ->
  [one] reagierte mit { $reaction }
  *[other] reagierten mit { $reaction }
      }
DIALTONE_EMOJI_PICKER_ADD_EMOJI_LABEL = Emoji hinzufügen
DIALTONE_EMOJI_PICKER_SEARCH_NO_RESULTS_LABEL = Keine Ergebnisse
DIALTONE_EMOJI_PICKER_SEARCH_RESULTS_LABEL = Suchergebnisse
DIALTONE_EMOJI_PICKER_SEARCH_PLACEHOLDER_LABEL = Suchen ...
DIALTONE_EMOJI_PICKER_SKIN_SELECTOR_BUTTON_TOOLTIP_LABEL = Standardhautton verändern
DIALTONE_EMOJI_PICKER_TABSET_RECENTLY_USED_LABEL = Zuletzt verwendet
DIALTONE_EMOJI_PICKER_TABSET_SMILEYS_AND_PEOPLE_LABEL = Smileys und Menschen
DIALTONE_EMOJI_PICKER_TABSET_NATURE_LABEL = Natur
DIALTONE_EMOJI_PICKER_TABSET_FOOD_LABEL = Essen
DIALTONE_EMOJI_PICKER_TABSET_ACTIVITY_LABEL = Aktivität
DIALTONE_EMOJI_PICKER_TABSET_TRAVEL_LABEL = Reisen
DIALTONE_EMOJI_PICKER_TABSET_OBJECTS_LABEL = Objekte
DIALTONE_EMOJI_PICKER_TABSET_SYMBOLS_LABEL = Symbole
DIALTONE_EMOJI_PICKER_TABSET_FLAGS_LABEL = Flaggen
DIALTONE_EMOJI_PICKER_TABSET_CUSTOM_LABEL = Benutzerdefiniert
DIALTONE_FEED_ITEM_PILL_ARIA_LABEL = Zum Vergrößern anklicken
DIALTONE_GENERAL_ROW_ACTIVE_VOICE_CHAT_TEXT = Aktiver Voice-Chat
DIALTONE_GENERAL_ROW_CALL_BUTTON_TOOLTIP = Anruf
DIALTONE_GENERAL_ROW_DND_TEXT_TOOLTIP = Bitte nicht stören
DIALTONE_GROUP_ROW_GROUP_COUNT_TEXT =
  { $count ->
  [1] 1 Benutzer
  *[other] { $count } Benutzer
      }
DIALTONE_IVR_NODE_MENU_BUTTON_ARIA_LABEL = Menü öffnen
DIALTONE_IVR_NODE_PROMPTMENU_ARIA_LABEL = Prompt-Menü-Knoten
DIALTONE_IVR_NODE_PROMPTCOLLECT_ARIA_LABEL = Prompterfassung-Knoten
DIALTONE_IVR_NODE_PROMPTPLAY_ARIA_LABEL = Promptwiedergabe-Knoten
DIALTONE_IVR_NODE_GOTOEXPERT_ARIA_LABEL = Zum Expertenknoten wechseln
DIALTONE_IVR_NODE_BRANCH_ARIA_LABEL = Zweigknoten
DIALTONE_IVR_NODE_GOTO_ARIA_LABEL = Zu Knoten gehen
DIALTONE_IVR_NODE_ASSIGN_ARIA_LABEL = Knoten zuweisen
DIALTONE_IVR_NODE_CUSTOMERDATA_ARIA_LABEL = Kundendaten-Knoten
DIALTONE_IVR_NODE_TRANSFER_ARIA_LABEL = Knoten übertragen
DIALTONE_IVR_NODE_HANGUP_ARIA_LABEL = Auflegen-Knoten
DIALTONE_MESSAGE_INPUT_SEND_BUTTON_ARIA_LABEL = Senden
DIALTONE_MESSAGE_INPUT_IMAGE_PICKER_BUTTON_ARIA_LABEL = Bild anhängen
DIALTONE_MESSAGE_INPUT_EMOJI_PICKER_BUTTON_ARIA_LABEL = Emoji auswählen
DIALTONE_MESSAGE_INPUT_CANCEL_BUTTON_ARIA_LABEL = ABBRECHEN
DIALTONE_MESSAGE_INPUT_BOLD_BUTTON_LABEL =
  .aria-label = Ausgewählten Text auf fett umschalten
  .tooltip-text = Fett
DIALTONE_MESSAGE_INPUT_ITALIC_BUTTON_LABEL =
  .aria-label = Ausgewählten Text auf kursiv umschalten
  .tooltip-text = Kursiv
DIALTONE_MESSAGE_INPUT_STRIKETHROUGH_BUTTON_LABEL =
  .aria-label = Markierten Text durchstreichen
  .tooltip-text = Durchstreichen
DIALTONE_MESSAGE_INPUT_BULLET_LIST_BUTTON_LABEL =
  .aria-label = Erstellen oder Bearbeiten einer Aufzählung für ausgewählten Text
  .tooltip-text = Aufzählung
DIALTONE_MESSAGE_INPUT_ORDERED_LIST_BUTTON_LABEL =
  .aria-label = Erstellen oder Bearbeiten einer geordneten Liste für ausgewählten Text
  .tooltip-text = Geordnete Liste
DIALTONE_MESSAGE_INPUT_BLOCK_QUOTE_BUTTON_LABEL =
  .aria-label = Erstellen oder Bearbeiten von Blockzitaten für ausgewählten Text
  .tooltip-text = Blockzitat
DIALTONE_MESSAGE_INPUT_CODE_BUTTON_LABEL =
  .aria-label = Erstellen oder Bearbeiten von Code für markierten Text
  .tooltip-text = Code
DIALTONE_MESSAGE_INPUT_CODE_BLOCK_BUTTON_LABEL =
  .aria-label = Erstellen oder Bearbeiten eines Codeblocks für ausgewählten Text
  .tooltip-text = Codeblock
DIALTONE_MESSAGE_INPUT_LINK_BUTTON_LABEL =
  .aria-label = Erstellen oder Bearbeiten eines Links für ausgewählten Text
  .tooltip-text = Link
DIALTONE_MESSAGE_INPUT_LINK_DIALOG_TITLE = Link hinzufügen
DIALTONE_MESSAGE_INPUT_LINK_TEXT_LABEL = Anzuzeigender Text (optional)
DIALTONE_MESSAGE_INPUT_LINK_LINK_LABEL = Link
DIALTONE_MESSAGE_INPUT_LINK_LINK_PLACEHOLDER = z. B. https://www.dialpad.com
DIALTONE_MESSAGE_INPUT_LINK_REMOVE_LABEL = Entfernen
DIALTONE_MESSAGE_INPUT_LINK_CANCEL_LABEL = ABBRECHEN
DIALTONE_MESSAGE_INPUT_LINK_CONFIRM_LABEL = Fertig
DIALTONE_PAGINATION_FIRST_PAGE = Erste Seite
DIALTONE_PAGINATION_PREVIOUS_PAGE = Vorherige Seite
DIALTONE_PAGINATION_NEXT_PAGE = Nächste Seite
DIALTONE_PAGINATION_LAST_PAGE = Letzte Seite
DIALTONE_PAGINATION_PAGE_NUMBER = Seitenzahl { $page }
DIALTONE_RICH_TEXT_EDITOR_EDIT_BUTTON_LABEL = Bearbeiten
DIALTONE_RICH_TEXT_EDITOR_OPEN_LINK_BUTTON_LABEL = Link öffnen
DIALTONE_RICH_TEXT_EDITOR_REMOVE_BUTTON_LABEL = Entfernen
DIALTONE_SETTINGS_MENU_DEFAULT_BUTTON_LABEL = Einstellungen
DIALTONE_SETTINGS_MENU_UPDATE_BUTTON_LABEL = Update
DIALTONE_UNREAD_PILL_MENTIONS_TEXT = Ungelesene Erwähnungen
DIALTONE_UNREAD_PILL_MESSAGES_TEXT = Ungelesene Nachrichten
# Storybook only
STORYBOOK_LANGUAGE_ENGLISH = Englisch
STORYBOOK_LANGUAGE_CHINESE = Chinesisch
STORYBOOK_LANGUAGE_DUTCH = Holländisch
STORYBOOK_LANGUAGE_FRENCH = Französisch
STORYBOOK_LANGUAGE_GERMAN = Deutsch
STORYBOOK_LANGUAGE_ITALIAN = Italienisch
STORYBOOK_LANGUAGE_JAPANESE = Japanisch
STORYBOOK_LANGUAGE_PORTUGUESE = Portugiesisch
STORYBOOK_LANGUAGE_RUSSIAN = Russisch
STORYBOOK_LANGUAGE_SPANISH = Spanisch
STORYBOOK_SET_LANGUAGE = Sprache einstellen
STORYBOOK_YOU = Sie selbst
STORYBOOK_REACTION_NAMES_2 = Olivia Chen, Benjamin Carter, Sophia Rodriguez, William Kim & Isabella Garcia
STORYBOOK_REACTION_NAMES_3 = Olivia Chen & { STORYBOOK_YOU }
