# Dialtone
DIALTONE_CLOSE_BUTTON =
  .aria-label = Ĉ£ůšά
  .title = Ĉ£ůšά
DIALTONE_BREADCRUMBS_ARIA_LABEL = ßřάëḍĉřøɱßš
DIALTONE_BUTTON_LOADING = £ůëḍīŋğ
DIALTONE_DATEPICKER_PREVIOUS_MONTH = Þřάʋīůøš ɱůŋ†ħ
DIALTONE_DATEPICKER_NEXT_MONTH = Ŋάχ† ɱůŋ†ħ
DIALTONE_DATEPICKER_PREVIOUS_YEAR = Þřάʋīůøš ýάëř
DIALTONE_DATEPICKER_NEXT_YEAR = Ŋάχ† ýάëř
DIALTONE_DATEPICKER_SELECT_DAY = Šά£άĉ† ḍëý
DIALTONE_DATEPICKER_CHANGE_TO = Ĉħëŋğά †ů

# Storybook only
STORYBOOK_LANGUAGE_ENGLISH = Άŋğ£īšħ
STORYBOOK_LANGUAGE_SPANISH = Šþëŋīšħ
STORYBOOK_LANGUAGE_DIALPADISTAN = Ḍīë£þëḍīš†ëŋ
STORYBOOK_SET_LANGUAGE = Šά† £ëŋğøëğά
