CLICK_TO_CLOSE = Ĉ£īĉʞ †ů ĉ£ůšά
CLICK_TO_OPEN = Ĉ£īĉʞ †ů ůþάŋ
ENGLISH = Άŋğ£īšħ
SPANISH = Šþëŋīšħ
DIALPADISTAN = Ḍīë£þëḍīš†ëŋ
SET_LANGUAGE = Šά† £ëŋğøëğά
CLOSE_BUTTON =
    .aria-label = Ĉ£ůšά
    .title = Ĉ£ůšά
BREADCRUMB_ARIA_LABEL = ßřάëḍĉřøɱßš
LOADING = £ůëḍīŋğ
PREVIOUS_MONTH = Þřάʋīůøš ɱůŋ†ħ
NEXT_MONTH = Ŋάχ† ɱůŋ†ħ
PREVIOUS_YEAR = Þřάʋīůøš ýάëř
NEXT_YEAR = Ŋάχ† ýάëř
SELECT_DAY = Šά£άĉ† ḍëý
CHANGE_TO = Ĉħëŋğά †ů
