# Dialtone
DIALTONE_CLOSE_BUTTON =
  .aria-label = Close
  .title = Close
DIALTONE_BREADCRUMBS_ARIA_LABEL = breadcrumbs
DIALTONE_BUTTON_LOADING = loading
DIALTONE_DATEPICKER_PREVIOUS_MONTH = Previous month
DIALTONE_DATEPICKER_NEXT_MONTH = Next month
DIALTONE_DATEPICKER_PREVIOUS_YEAR = Previous year
DIALTONE_DATEPICKER_NEXT_YEAR = Next year
DIALTONE_DATEPICKER_SELECT_DAY = Select day
DIALTONE_DATEPICKER_CHANGE_TO = Change to
DIALTONE_CALLBAR_BUTTON_WITH_DROPDOWN_ARROW_BUTTON_ARIA_LABEL = Open dropdown
DIALTONE_CALLBAR_BUTTON_WITH_POPOVER_ARROW_BUTTON_ARIA_LABEL = Open popover

DIALTONE_IVR_NODE_MENU_BUTTON_ARIA_LABEL = Open menu
DIALTONE_IVR_NODE_PROMPTMENU_ARIA_LABEL = prompt menu node
DIALTONE_IVR_NODE_PROMPTCOLLECT_ARIA_LABEL = prompt collect node
DIALTONE_IVR_NODE_PROMPTPLAY_ARIA_LABEL = prompt play node
DIALTONE_IVR_NODE_GOTOEXPERT_ARIA_LABEL = go to expert node
DIALTONE_IVR_NODE_BRANCH_ARIA_LABEL = branch node
DIALTONE_IVR_NODE_GOTO_ARIA_LABEL = go to node
DIALTONE_IVR_NODE_ASSIGN_ARIA_LABEL = assign node
DIALTONE_IVR_NODE_CUSTOMERDATA_ARIA_LABEL = customer data node
DIALTONE_IVR_NODE_TRANSFER_ARIA_LABEL = transfer node
DIALTONE_IVR_NODE_HANGUP_ARIA_LABEL = hangup node

DIALTONE_ATTACHMENT_CAROUSEL_CLICK_TO_OPEN_ARIA_LABEL = Click to open
DIALTONE_ATTACHMENT_CAROUSEL_PROGRESS_BAR_ARIA_LABEL = Uploading
DIALTONE_ATTACHMENT_CAROUSEL_LEFT_ARROW_ARIA_LABEL = Previous
DIALTONE_ATTACHMENT_CAROUSEL_RIGHT_ARROW_ARIA_LABEL = Next

DIALTONE_EDITOR_CONFIRM_SET_LINK_BUTTON =
  .label = Confirm
  .aria-label = Confirm set link
DIALTONE_EDITOR_REMOVE_LINK_BUTTON =
  .label = Remove
  .aria-label = Remove link
DIALTONE_EDITOR_CANCEL_SET_LINK_BUTTON =
  .label = Cancel
  .aria-label = Cancel set link

DIALTONE_EDITOR_QUICK_REPLY_BUTTON_LABEL = Quick Reply
DIALTONE_EDITOR_BOLD_BUTTON_LABEL = Bold
DIALTONE_EDITOR_ITALICS_BUTTON_LABEL = Italics
DIALTONE_EDITOR_UNDERLINE_BUTTON_LABEL = Underline
DIALTONE_EDITOR_STRIKE_BUTTON_LABEL = Strike
DIALTONE_EDITOR_ALIGN_LEFT_BUTTON_LABEL = Align Left
DIALTONE_EDITOR_ALIGN_CENTER_BUTTON_LABEL = Align Center
DIALTONE_EDITOR_ALIGN_RIGHT_BUTTON_LABEL = Align Right
DIALTONE_EDITOR_ALIGN_JUSTIFY_BUTTON_LABEL = Align Justify
DIALTONE_EDITOR_BULLET_LIST_BUTTON_LABEL = Bullet List
DIALTONE_EDITOR_ORDERED_LIST_BUTTON_LABEL = Ordered List
DIALTONE_EDITOR_QUOTE_BUTTON_LABEL = Quote
DIALTONE_EDITOR_CODE_BUTTON_LABEL = Code
DIALTONE_EDITOR_IMAGE_BUTTON_LABEL = Image
DIALTONE_EDITOR_LINK_BUTTON_LABEL = Link
DIALTONE_EDITOR_ADD_LINK_BUTTON =
  .title = Add Link
  .aria-label = Input field to add link

DIALTONE_EMOJI_ROW_REACTION_LABEL =
  { $reactionCount ->
  *[other] { $selected ->
  *[false] { $reactionCount } people reacted with { $reaction }.
  [true] { $reactionCount } people included you reacted with { $reaction }.
      }
  [one] { $selected ->
  *[false] { $name } reacted with { $reaction }.
  [true] You reacted with { $reaction }.
      }
    }

DIALTONE_FEED_ITEM_PILL_ARIA_LABEL =
  .aria-label = Click to expand
  .title = Click to expand


# Storybook only
STORYBOOK_LANGUAGE_ENGLISH = English
STORYBOOK_LANGUAGE_SPANISH = Spanish
STORYBOOK_LANGUAGE_DIALPADISTAN = Dialpadistan
STORYBOOK_SET_LANGUAGE = Set language
