# Dialtone
DIALTONE_CLOSE_BUTTON = Click to close
DIALTONE_BREADCRUMBS_ARIA_LABEL = breadcrumbs
DIALTONE_BUTTON_LOADING = loading
DIALTONE_UNREAD_MESSAGE_COUNT_TEXT =
  { $unreadCount ->
    [0] No unread messages
    [1] 1 unread message
    *[other] {$unreadCount} unread messages
  }
DIALTONE_UNREAD_MENTION_COUNT_TEXT =
  { $unreadCount ->
    [0] No unread mentions
    [1] 1 unread mention
    *[other] {$unreadCount} unread mentions
  }
DIALTONE_TYPING_TEXT = Typing

DIALTONE_ATTACHMENT_CAROUSEL_CLICK_TO_OPEN_ARIA_LABEL = Click to open
DIALTONE_ATTACHMENT_CAROUSEL_PROGRESS_BAR_ARIA_LABEL = Uploading
DIALTONE_ATTACHMENT_CAROUSEL_LEFT_ARROW_ARIA_LABEL = Previous
DIALTONE_ATTACHMENT_CAROUSEL_RIGHT_ARROW_ARIA_LABEL = Next

DIALTONE_CALLBAR_BUTTON_WITH_DROPDOWN_ARROW_BUTTON_ARIA_LABEL = Open dropdown
DIALTONE_CALLBAR_BUTTON_WITH_POPOVER_ARROW_BUTTON_ARIA_LABEL = Open popover

DIALTONE_CONTACT_CENTERS_ROW_MENU_BUTTON_LABEL = Open menu

DIALTONE_DATEPICKER_PREVIOUS_MONTH = Previous month
DIALTONE_DATEPICKER_NEXT_MONTH = Next month
DIALTONE_DATEPICKER_PREVIOUS_YEAR = Previous year
DIALTONE_DATEPICKER_NEXT_YEAR = Next year
DIALTONE_DATEPICKER_SELECT_DAY = Select day
DIALTONE_DATEPICKER_CHANGE_TO = Change to

DIALTONE_EDITOR_CONFIRM_SET_LINK_BUTTON =
  .title = Confirm
  .aria-label = Confirm set link
DIALTONE_EDITOR_REMOVE_LINK_BUTTON =
  .title = Remove
  .aria-label = Remove link
DIALTONE_EDITOR_CANCEL_SET_LINK_BUTTON =
  .title = Cancel
  .aria-label = Cancel set link

DIALTONE_EDITOR_QUICK_REPLY_BUTTON_LABEL = Quick reply
DIALTONE_EDITOR_BOLD_BUTTON_LABEL = Bold
DIALTONE_EDITOR_ITALICS_BUTTON_LABEL = Italics
DIALTONE_EDITOR_UNDERLINE_BUTTON_LABEL = Underline
DIALTONE_EDITOR_STRIKE_BUTTON_LABEL = Strike
DIALTONE_EDITOR_ALIGN_LEFT_BUTTON_LABEL = Align Left
DIALTONE_EDITOR_ALIGN_CENTER_BUTTON_LABEL = Align Center
DIALTONE_EDITOR_ALIGN_RIGHT_BUTTON_LABEL = Align Right
DIALTONE_EDITOR_ALIGN_JUSTIFY_BUTTON_LABEL = Align Justify
DIALTONE_EDITOR_BULLET_LIST_BUTTON_LABEL = Bullet List
DIALTONE_EDITOR_ORDERED_LIST_BUTTON_LABEL = Ordered List
DIALTONE_EDITOR_QUOTE_BUTTON_LABEL = Quote
DIALTONE_EDITOR_CODE_BUTTON_LABEL = Code
DIALTONE_EDITOR_IMAGE_BUTTON_LABEL = Image
DIALTONE_EDITOR_LINK_BUTTON_LABEL = Link
DIALTONE_EDITOR_ADD_LINK_BUTTON =
  .title = Add Link
  .aria-label = Input field to add link

DIALTONE_EMOJI_ROW_REACTION_LABEL =
  { $reactionCount ->
    *[other] { $selected ->
      *[false] { $reactionCount } people reacted with { $reaction }.
      [true] { $reactionCount } people including you reacted with { $reaction }.
    }
    [one] { $selected ->
      *[false] { $name } reacted with { $reaction }.
      [true] You reacted with { $reaction }.
    }
  }

DIALTONE_EMOJI_PICKER_ADD_EMOJI_LABEL = Add emoji
DIALTONE_EMOJI_PICKER_SEARCH_NO_RESULTS_LABEL = No results
DIALTONE_EMOJI_PICKER_SEARCH_RESULTS_LABEL = Search results
DIALTONE_EMOJI_PICKER_SEARCH_PLACEHOLDER_LABEL = Search...
DIALTONE_EMOJI_PICKER_SKIN_SELECTOR_BUTTON_TOOLTIP_LABEL = Change default skin tone
DIALTONE_EMOJI_PICKER_TABSET_RECENTLY_USED_LABEL = Most recently used
DIALTONE_EMOJI_PICKER_TABSET_SMILEYS_AND_PEOPLE_LABEL = Smileys and people
DIALTONE_EMOJI_PICKER_TABSET_NATURE_LABEL = Nature
DIALTONE_EMOJI_PICKER_TABSET_FOOD_LABEL = Food
DIALTONE_EMOJI_PICKER_TABSET_ACTIVITY_LABEL = Activity
DIALTONE_EMOJI_PICKER_TABSET_TRAVEL_LABEL = Travel
DIALTONE_EMOJI_PICKER_TABSET_OBJECTS_LABEL = Objects
DIALTONE_EMOJI_PICKER_TABSET_SYMBOLS_LABEL = Symbols
DIALTONE_EMOJI_PICKER_TABSET_FLAGS_LABEL = Flags
DIALTONE_EMOJI_PICKER_TABSET_CUSTOM_LABEL = Custom

DIALTONE_FEED_ITEM_PILL_ARIA_LABEL = Click to expand

DIALTONE_GENERAL_ROW_ACTIVE_VOICE_CHAT_TEXT = Active voice chat
DIALTONE_GENERAL_ROW_CALL_BUTTON_TOOLTIP = Call
DIALTONE_GENERAL_ROW_DND_TEXT_TOOLTIP = Do not disturb

DIALTONE_GROUP_ROW_GROUP_COUNT_TEXT =
  { $count ->
    [1] 1 user
    *[other] {$count} users
  }

DIALTONE_IVR_NODE_MENU_BUTTON_ARIA_LABEL = Open menu
DIALTONE_IVR_NODE_PROMPTMENU_ARIA_LABEL = prompt menu node
DIALTONE_IVR_NODE_PROMPTCOLLECT_ARIA_LABEL = prompt collect node
DIALTONE_IVR_NODE_PROMPTPLAY_ARIA_LABEL = prompt play node
DIALTONE_IVR_NODE_GOTOEXPERT_ARIA_LABEL = go to expert node
DIALTONE_IVR_NODE_BRANCH_ARIA_LABEL = branch node
DIALTONE_IVR_NODE_GOTO_ARIA_LABEL = go to node
DIALTONE_IVR_NODE_ASSIGN_ARIA_LABEL = assign node
DIALTONE_IVR_NODE_CUSTOMERDATA_ARIA_LABEL = customer data node
DIALTONE_IVR_NODE_TRANSFER_ARIA_LABEL = transfer node
DIALTONE_IVR_NODE_HANGUP_ARIA_LABEL = hangup node

DIALTONE_MESSAGE_INPUT_SEND_BUTTON_ARIA_LABEL = Send
DIALTONE_MESSAGE_INPUT_IMAGE_PICKER_BUTTON_ARIA_LABEL = Attach Image
DIALTONE_MESSAGE_INPUT_EMOJI_PICKER_BUTTON_ARIA_LABEL = Select Emoji
DIALTONE_MESSAGE_INPUT_CANCEL_BUTTON_ARIA_LABEL = Cancel
DIALTONE_MESSAGE_INPUT_BOLD_BUTTON_LABEL =
  .aria-label = Toggle bold on selected text
  .tooltip-text = Bold
DIALTONE_MESSAGE_INPUT_ITALIC_BUTTON_LABEL =
  .aria-label = Toggle italic on selected text
  .tooltip-text = Italic
DIALTONE_MESSAGE_INPUT_STRIKETHROUGH_BUTTON_LABEL =
  .aria-label = Toggle strikethrough on selected text
  .tooltip-text = Strikethrough
DIALTONE_MESSAGE_INPUT_BULLET_LIST_BUTTON_LABEL =
  .aria-label = Create or edit bullet list on selected text
  .tooltip-text = Bullet list
DIALTONE_MESSAGE_INPUT_ORDERED_LIST_BUTTON_LABEL =
  .aria-label = Create or edit ordered list on selected text
  .tooltip-text = Ordered list
DIALTONE_MESSAGE_INPUT_BLOCK_QUOTE_BUTTON_LABEL =
  .aria-label = Create or edit block quote on selected text
  .tooltip-text = Block quote
DIALTONE_MESSAGE_INPUT_CODE_BUTTON_LABEL =
  .aria-label = Create or edit code on selected text
  .tooltip-text = Code
DIALTONE_MESSAGE_INPUT_CODE_BLOCK_BUTTON_LABEL =
  .aria-label = Create or edit code block on selected text
  .tooltip-text = Code block
DIALTONE_MESSAGE_INPUT_LINK_BUTTON_LABEL =
  .aria-label = Create or edit link on selected text
  .tooltip-text = Link
DIALTONE_MESSAGE_INPUT_LINK_DIALOG_TITLE = Add a link
DIALTONE_MESSAGE_INPUT_LINK_TEXT_LABEL = Text to display (optional)
DIALTONE_MESSAGE_INPUT_LINK_LINK_LABEL = Link
DIALTONE_MESSAGE_INPUT_LINK_LINK_PLACEHOLDER = e.g. https://www.dialpad.com
DIALTONE_MESSAGE_INPUT_LINK_REMOVE_LABEL = Remove
DIALTONE_MESSAGE_INPUT_LINK_CANCEL_LABEL = Cancel
DIALTONE_MESSAGE_INPUT_LINK_CONFIRM_LABEL = Done

DIALTONE_PAGINATION_FIRST_PAGE = First page
DIALTONE_PAGINATION_PREVIOUS_PAGE = Previous page
DIALTONE_PAGINATION_NEXT_PAGE = Next page
DIALTONE_PAGINATION_LAST_PAGE = Last page
DIALTONE_PAGINATION_PAGE_NUMBER = Page number {$page}

DIALTONE_RICH_TEXT_EDITOR_EDIT_BUTTON_LABEL = Edit
DIALTONE_RICH_TEXT_EDITOR_OPEN_LINK_BUTTON_LABEL = Open link
DIALTONE_RICH_TEXT_EDITOR_REMOVE_BUTTON_LABEL = Remove

DIALTONE_SETTINGS_MENU_DEFAULT_BUTTON_LABEL = Settings
DIALTONE_SETTINGS_MENU_UPDATE_BUTTON_LABEL = Update

DIALTONE_UNREAD_PILL_MENTIONS_TEXT = Unread mentions
DIALTONE_UNREAD_PILL_MESSAGES_TEXT = Unread messages

# Storybook only
STORYBOOK_LANGUAGE_ENGLISH = English
STORYBOOK_LANGUAGE_CHINESE = Chinese
STORYBOOK_LANGUAGE_DUTCH = Dutch
STORYBOOK_LANGUAGE_FRENCH = French
STORYBOOK_LANGUAGE_GERMAN = German
STORYBOOK_LANGUAGE_ITALIAN = Italian
STORYBOOK_LANGUAGE_JAPANESE = Japanese
STORYBOOK_LANGUAGE_PORTUGUESE = Portuguese
STORYBOOK_LANGUAGE_RUSSIAN = Russian
STORYBOOK_LANGUAGE_SPANISH = Spanish
STORYBOOK_SET_LANGUAGE = Set language
