CLICK_TO_CLOSE = Click para cerrar
CLICK_TO_OPEN = Click para abrir
ENGLISH = Inglés
SPANISH = Español
DIALPADISTAN = Dialpadistan
SET_LANGUAGE = Cambiar idioma
CLOSE_BUTTON =
  .aria-label = Cerrar
  .title = Cerrar
BREADCRUMB_ARIA_LABEL = lista de enlaces
LOADING = cargando
