# Dialtone
DIALTONE_CLOSE_BUTTON = Haga clic para cerrar
DIALTONE_BREADCRUMBS_ARIA_LABEL = Breadcrumbs
DIALTONE_LOADING = Cargando
DIALTONE_UNREAD_MESSAGE_COUNT_TEXT =
    { $unreadCount ->
        [0] No hay mensajes sin leer
        [1] 1 mensaje sin leer
       *[other] { $unreadCount } mensajes sin leer
    }
DIALTONE_UNREAD_MENTION_COUNT_TEXT =
    { $unreadCount ->
        [0] No hay menciones sin leer
        [1] 1 mención sin leer
       *[other] { $unreadCount } menciones sin leer
    }
DIALTONE_TYPING_TEXT = Está escribiendo
DIALTONE_ATTACHMENT_CAROUSEL_CLICK_TO_OPEN_ARIA_LABEL = Haga clic para abrir
DIALTONE_ATTACHMENT_CAROUSEL_PROGRESS_BAR_ARIA_LABEL = Subiendo
DIALTONE_ATTACHMENT_CAROUSEL_LEFT_ARROW_ARIA_LABEL = Anterior
DIALTONE_ATTACHMENT_CAROUSEL_RIGHT_ARROW_ARIA_LABEL = Siguiente
DIALTONE_CALLBAR_BUTTON_WITH_DROPDOWN_ARROW_BUTTON_ARIA_LABEL = Abrir menú desplegable
DIALTONE_CALLBAR_BUTTON_WITH_POPOVER_ARROW_BUTTON_ARIA_LABEL = Abrir ventana emergente
DIALTONE_CONTACT_CENTERS_ROW_MENU_BUTTON_LABEL = Abrir menú
DIALTONE_DATEPICKER_PREVIOUS_MONTH = Mes anterior
DIALTONE_DATEPICKER_NEXT_MONTH = el próximo mes
DIALTONE_DATEPICKER_PREVIOUS_YEAR = Año anterior
DIALTONE_DATEPICKER_NEXT_YEAR = el próximo año
DIALTONE_DATEPICKER_SELECT_DAY = Seleccionar día
DIALTONE_DATEPICKER_CHANGE_TO = Cambiar a
DIALTONE_EDITOR_CONFIRM_SET_LINK_BUTTON =
    .title = Confirmar
    .aria-label = Confirmar enlace establecido
DIALTONE_EDITOR_REMOVE_LINK_BUTTON =
    .title = Eliminar
    .aria-label = Eliminar enlace
DIALTONE_EDITOR_CANCEL_SET_LINK_BUTTON =
    .title = cancelar
    .aria-label = Cancelar enlace establecido
DIALTONE_EDITOR_QUICK_REPLY_BUTTON_LABEL = Plantilla
DIALTONE_EDITOR_BOLD_BUTTON_LABEL = Negrita
DIALTONE_EDITOR_ITALICS_BUTTON_LABEL = Cursiva
DIALTONE_EDITOR_UNDERLINE_BUTTON_LABEL = Subrayado
DIALTONE_EDITOR_STRIKE_BUTTON_LABEL = Tachado
DIALTONE_EDITOR_ALIGN_LEFT_BUTTON_LABEL = Alinear a la izquierda
DIALTONE_EDITOR_ALIGN_CENTER_BUTTON_LABEL = Alinear al centro
DIALTONE_EDITOR_ALIGN_RIGHT_BUTTON_LABEL = Alinear a la derecha
DIALTONE_EDITOR_ALIGN_JUSTIFY_BUTTON_LABEL = Alinear y justificar
DIALTONE_EDITOR_BULLET_LIST_BUTTON_LABEL = Lista de viñetas
DIALTONE_EDITOR_ORDERED_LIST_BUTTON_LABEL = Lista ordenada
DIALTONE_EDITOR_QUOTE_BUTTON_LABEL = Cita
DIALTONE_EDITOR_CODE_BUTTON_LABEL = Código
DIALTONE_EDITOR_IMAGE_BUTTON_LABEL = Imagen
DIALTONE_EDITOR_LINK_BUTTON_LABEL = Enlace
DIALTONE_EDITOR_ADD_LINK_BUTTON =
    .title = Agregar enlace
    .aria-label = Campo de entrada para agregar enlace
DIALTONE_EMOJI_PICKER_ADD_EMOJI_LABEL = Agregar emoji
DIALTONE_EMOJI_PICKER_SEARCH_NO_RESULTS_LABEL = No hay resultados
DIALTONE_EMOJI_PICKER_SEARCH_RESULTS_LABEL = resultados de búsqueda
DIALTONE_EMOJI_PICKER_SEARCH_PLACEHOLDER_LABEL = Buscar...
DIALTONE_EMOJI_PICKER_SKIN_SELECTOR_BUTTON_TOOLTIP_LABEL = Cambiar el tono de piel predeterminado
DIALTONE_EMOJI_PICKER_TABSET_RECENTLY_USED_LABEL = Usado más recientemente
DIALTONE_EMOJI_PICKER_TABSET_SMILEYS_AND_PEOPLE_LABEL = Emoticonos y personas
DIALTONE_EMOJI_PICKER_TABSET_NATURE_LABEL = naturaleza
DIALTONE_EMOJI_PICKER_TABSET_FOOD_LABEL = alimento
DIALTONE_EMOJI_PICKER_TABSET_ACTIVITY_LABEL = Actividad
DIALTONE_EMOJI_PICKER_TABSET_TRAVEL_LABEL = viaje
DIALTONE_EMOJI_PICKER_TABSET_OBJECTS_LABEL = Objetos
DIALTONE_EMOJI_PICKER_TABSET_SYMBOLS_LABEL = Símbolos
DIALTONE_EMOJI_PICKER_TABSET_FLAGS_LABEL = Banderas
DIALTONE_EMOJI_PICKER_TABSET_CUSTOM_LABEL = personalizado
DIALTONE_FEED_ITEM_PILL_ARIA_LABEL = Haga clic para ampliar
DIALTONE_GENERAL_ROW_ACTIVE_VOICE_CHAT_TEXT = Chat de voz activo
DIALTONE_GENERAL_ROW_CALL_BUTTON_TOOLTIP = Llamar
DIALTONE_GENERAL_ROW_DND_TEXT_TOOLTIP = No molestar
DIALTONE_GROUP_ROW_GROUP_COUNT_TEXT =
    { $count ->
        [1] 1 usuario
       *[other] { $count } usuarios
    }
DIALTONE_IVR_NODE_MENU_BUTTON_ARIA_LABEL = Abrir menú
DIALTONE_IVR_NODE_PROMPTMENU_ARIA_LABEL = nodo de menú de indicación
DIALTONE_IVR_NODE_PROMPTCOLLECT_ARIA_LABEL = nodo de recopilación rápida
DIALTONE_IVR_NODE_PROMPTPLAY_ARIA_LABEL = nodo de reproducción rápida
DIALTONE_IVR_NODE_GOTOEXPERT_ARIA_LABEL = ir al nodo experto
DIALTONE_IVR_NODE_BRANCH_ARIA_LABEL = nodo de rama
DIALTONE_IVR_NODE_GOTO_ARIA_LABEL = ir al nodo
DIALTONE_IVR_NODE_ASSIGN_ARIA_LABEL = asignar nodo
DIALTONE_IVR_NODE_CUSTOMERDATA_ARIA_LABEL = nodo de datos del cliente
DIALTONE_IVR_NODE_TRANSFER_ARIA_LABEL = nodo de transferencia
DIALTONE_IVR_NODE_HANGUP_ARIA_LABEL = nodo de la función de colgar
DIALTONE_MESSAGE_INPUT_SEND_BUTTON_ARIA_LABEL = enviar
DIALTONE_MESSAGE_INPUT_IMAGE_PICKER_BUTTON_ARIA_LABEL = Anexar imagen
DIALTONE_MESSAGE_INPUT_EMOJI_PICKER_BUTTON_ARIA_LABEL = Seleccionar emoji
DIALTONE_MESSAGE_INPUT_CANCEL_BUTTON_ARIA_LABEL = cancelar
DIALTONE_MESSAGE_INPUT_BOLD_BUTTON_LABEL =
    .aria-label = Active la negrita en el texto seleccionado
    .tooltip-text = Negrita
DIALTONE_MESSAGE_INPUT_ITALIC_BUTTON_LABEL =
    .aria-label = Active la cursiva en el texto seleccionado
    .tooltip-text = Cursiva
DIALTONE_MESSAGE_INPUT_STRIKETHROUGH_BUTTON_LABEL =
    .aria-label = Active el tachado del texto seleccionado
    .tooltip-text = Tachado
DIALTONE_MESSAGE_INPUT_BULLET_LIST_BUTTON_LABEL =
    .aria-label = Cree o edite una lista de viñetas en el texto seleccionado
    .tooltip-text = Lista de viñetas
DIALTONE_MESSAGE_INPUT_ORDERED_LIST_BUTTON_LABEL =
    .aria-label = Cree o edite una lista ordenada en el texto seleccionado
    .tooltip-text = Lista ordenada
DIALTONE_MESSAGE_INPUT_BLOCK_QUOTE_BUTTON_LABEL =
    .aria-label = Cree o edite una cita en bloque en el texto seleccionado
    .tooltip-text = Cita en bloque
DIALTONE_MESSAGE_INPUT_CODE_BUTTON_LABEL =
    .aria-label = Cree o edite un código en el texto seleccionado
    .tooltip-text = Código
DIALTONE_MESSAGE_INPUT_CODE_BLOCK_BUTTON_LABEL =
    .aria-label = Cree o edite un bloque de código en el texto seleccionado
    .tooltip-text = Bloque de código
DIALTONE_MESSAGE_INPUT_LINK_BUTTON_LABEL =
    .aria-label = Cree o edite un enlace en el texto seleccionado
    .tooltip-text = Enlace
DIALTONE_MESSAGE_INPUT_LINK_DIALOG_TITLE = Agregar un enlace
DIALTONE_MESSAGE_INPUT_LINK_TEXT_LABEL = Texto para mostrar (opcional)
DIALTONE_MESSAGE_INPUT_LINK_LINK_LABEL = Enlace
DIALTONE_MESSAGE_INPUT_LINK_LINK_PLACEHOLDER = por ejemplo, https://www.dialpad.com
DIALTONE_MESSAGE_INPUT_LINK_REMOVE_LABEL = Eliminar
DIALTONE_MESSAGE_INPUT_LINK_CANCEL_LABEL = cancelar
DIALTONE_MESSAGE_INPUT_LINK_CONFIRM_LABEL = Listo
DIALTONE_PAGINATION_FIRST_PAGE = Nombre
DIALTONE_PAGINATION_PREVIOUS_PAGE = Página anterior
DIALTONE_PAGINATION_NEXT_PAGE = Página siguiente
DIALTONE_PAGINATION_LAST_PAGE = Última página
DIALTONE_PAGINATION_PAGE_NUMBER = Número de página { $page }
DIALTONE_RICH_TEXT_EDITOR_EDIT_BUTTON_LABEL = Editar
DIALTONE_RICH_TEXT_EDITOR_OPEN_LINK_BUTTON_LABEL = Abrir enlace
DIALTONE_RICH_TEXT_EDITOR_REMOVE_BUTTON_LABEL = Eliminar
DIALTONE_SETTINGS_MENU_DEFAULT_BUTTON_LABEL = configuración
DIALTONE_SETTINGS_MENU_UPDATE_BUTTON_LABEL = Actualizar
DIALTONE_UNREAD_PILL_MENTIONS_TEXT = Menciones sin leer
DIALTONE_UNREAD_PILL_MESSAGES_TEXT = Mensajes sin leer
# Storybook only
STORYBOOK_LANGUAGE_ENGLISH = Inglés
STORYBOOK_LANGUAGE_CHINESE = Chino
STORYBOOK_LANGUAGE_DUTCH = Holandés
STORYBOOK_LANGUAGE_FRENCH = Francés
STORYBOOK_LANGUAGE_GERMAN = Alemán
STORYBOOK_LANGUAGE_ITALIAN = Italiano
STORYBOOK_LANGUAGE_JAPANESE = Japonés
STORYBOOK_LANGUAGE_PORTUGUESE = Portugués
STORYBOOK_LANGUAGE_RUSSIAN = Ruso
STORYBOOK_LANGUAGE_SPANISH = Español
STORYBOOK_SET_LANGUAGE = Establecer idioma
