# Dialtone
DIALTONE_CLOSE_BUTTON = Cliquez pour fermer
DIALTONE_BREADCRUMBS_ARIA_LABEL = Breadcrumbs
DIALTONE_LOADING = En cours de chargement
DIALTONE_UNREAD_MESSAGE_COUNT_TEXT =
    { $unreadCount ->
        [0] Aucun message non lu
        [1] 1 message non lu
       *[other] { $unreadCount } messages non lus
    }
DIALTONE_UNREAD_MENTION_COUNT_TEXT =
    { $unreadCount ->
        [0] Aucune mention non lue
        [1] 1 mention non lue
       *[other] { $unreadCount } mentions non lues
    }
DIALTONE_TYPING_TEXT = Est en train d’écrire
DIALTONE_ATTACHMENT_CAROUSEL_CLICK_TO_OPEN_ARIA_LABEL = Cliquez pour ouvrir
DIALTONE_ATTACHMENT_CAROUSEL_PROGRESS_BAR_ARIA_LABEL = Téléchargement en cours
DIALTONE_ATTACHMENT_CAROUSEL_LEFT_ARROW_ARIA_LABEL = Précédent
DIALTONE_ATTACHMENT_CAROUSEL_RIGHT_ARROW_ARIA_LABEL = Suivant
DIALTONE_CALLBAR_BUTTON_WITH_DROPDOWN_ARROW_BUTTON_ARIA_LABEL = Ouvrir le menu déroulant
DIALTONE_CALLBAR_BUTTON_WITH_POPOVER_ARROW_BUTTON_ARIA_LABEL = Ouvrir le popover
DIALTONE_CONTACT_CENTERS_ROW_MENU_BUTTON_LABEL = Ouvrir le menu
DIALTONE_DATEPICKER_PREVIOUS_MONTH = Mois précédent
DIALTONE_DATEPICKER_NEXT_MONTH = le mois prochain
DIALTONE_DATEPICKER_PREVIOUS_YEAR = Année précédente
DIALTONE_DATEPICKER_NEXT_YEAR = l'année prochaine
DIALTONE_DATEPICKER_SELECT_DAY = Sélectionnez le jour
DIALTONE_DATEPICKER_CHANGE_TO = Passez à
DIALTONE_EDITOR_CONFIRM_SET_LINK_BUTTON =
    .title = Confirmer
    .aria-label = Confirmer le lien défini
DIALTONE_EDITOR_REMOVE_LINK_BUTTON =
    .title = Supprimer
    .aria-label = Supprimer le lien
DIALTONE_EDITOR_CANCEL_SET_LINK_BUTTON =
    .title = Annuler
    .aria-label = Annuler le lien défini
DIALTONE_EDITOR_QUICK_REPLY_BUTTON_LABEL = Modèle
DIALTONE_EDITOR_BOLD_BUTTON_LABEL = Gras
DIALTONE_EDITOR_ITALICS_BUTTON_LABEL = Italique
DIALTONE_EDITOR_UNDERLINE_BUTTON_LABEL = Souligner
DIALTONE_EDITOR_STRIKE_BUTTON_LABEL = Barré
DIALTONE_EDITOR_ALIGN_LEFT_BUTTON_LABEL = Aligner à gauche
DIALTONE_EDITOR_ALIGN_CENTER_BUTTON_LABEL = Aligner au centre
DIALTONE_EDITOR_ALIGN_RIGHT_BUTTON_LABEL = Aligner à droite
DIALTONE_EDITOR_ALIGN_JUSTIFY_BUTTON_LABEL = Justifier
DIALTONE_EDITOR_BULLET_LIST_BUTTON_LABEL = Liste à puces
DIALTONE_EDITOR_ORDERED_LIST_BUTTON_LABEL = Liste numérotée
DIALTONE_EDITOR_QUOTE_BUTTON_LABEL = Citation
DIALTONE_EDITOR_CODE_BUTTON_LABEL = Code
DIALTONE_EDITOR_IMAGE_BUTTON_LABEL = Image
DIALTONE_EDITOR_LINK_BUTTON_LABEL = Lien
DIALTONE_EDITOR_ADD_LINK_BUTTON =
    .title = Ajouter un lien
    .aria-label = Champ de saisie pour ajouter un lien
DIALTONE_EMOJI_ROW_REACTION_LABEL = { $names } réagi avec { $reaction }
DIALTONE_EMOJI_PICKER_ADD_EMOJI_LABEL = Ajouter un émoji
DIALTONE_EMOJI_PICKER_SEARCH_NO_RESULTS_LABEL = Aucun résultat
DIALTONE_EMOJI_PICKER_SEARCH_RESULTS_LABEL = résultats de la recherche
DIALTONE_EMOJI_PICKER_SEARCH_PLACEHOLDER_LABEL = Rechercher...
DIALTONE_EMOJI_PICKER_SKIN_SELECTOR_BUTTON_TOOLTIP_LABEL = Modifier la couleur de peau par défaut
DIALTONE_EMOJI_PICKER_TABSET_RECENTLY_USED_LABEL = Dernière utilisation
DIALTONE_EMOJI_PICKER_TABSET_SMILEYS_AND_PEOPLE_LABEL = Smileys et personnes
DIALTONE_EMOJI_PICKER_TABSET_NATURE_LABEL = Nature
DIALTONE_EMOJI_PICKER_TABSET_FOOD_LABEL = Alimentation
DIALTONE_EMOJI_PICKER_TABSET_ACTIVITY_LABEL = Activité
DIALTONE_EMOJI_PICKER_TABSET_TRAVEL_LABEL = Voyage
DIALTONE_EMOJI_PICKER_TABSET_OBJECTS_LABEL = Objets
DIALTONE_EMOJI_PICKER_TABSET_SYMBOLS_LABEL = Symboles
DIALTONE_EMOJI_PICKER_TABSET_FLAGS_LABEL = Drapeaux
DIALTONE_EMOJI_PICKER_TABSET_CUSTOM_LABEL = Personnalisé
DIALTONE_FEED_ITEM_PILL_ARIA_LABEL = Cliquez pour agrandir
DIALTONE_GENERAL_ROW_ACTIVE_VOICE_CHAT_TEXT = Chat vocal actif
DIALTONE_GENERAL_ROW_CALL_BUTTON_TOOLTIP = Appel
DIALTONE_GENERAL_ROW_DND_TEXT_TOOLTIP = Ne pas déranger
DIALTONE_GROUP_ROW_GROUP_COUNT_TEXT =
    { $count ->
        [1] 1 utilisateur
       *[other] { $count } utilisateurs
    }
DIALTONE_IVR_NODE_MENU_BUTTON_ARIA_LABEL = Ouvrir le menu
DIALTONE_IVR_NODE_PROMPTMENU_ARIA_LABEL = nœud de menu d'invite
DIALTONE_IVR_NODE_PROMPTCOLLECT_ARIA_LABEL = nœud de collecte d'invite
DIALTONE_IVR_NODE_PROMPTPLAY_ARIA_LABEL = nœud de lecture d'invite
DIALTONE_IVR_NODE_GOTOEXPERT_ARIA_LABEL = nœud de transfert vers un expert
DIALTONE_IVR_NODE_BRANCH_ARIA_LABEL = nœud de branchement
DIALTONE_IVR_NODE_GOTO_ARIA_LABEL = nœud de redirection
DIALTONE_IVR_NODE_ASSIGN_ARIA_LABEL = nœud d'affectation
DIALTONE_IVR_NODE_CUSTOMERDATA_ARIA_LABEL = nœud de données clients
DIALTONE_IVR_NODE_TRANSFER_ARIA_LABEL = nœud de transfert
DIALTONE_IVR_NODE_HANGUP_ARIA_LABEL = nœud de raccrochage
DIALTONE_MESSAGE_INPUT_SEND_BUTTON_ARIA_LABEL = Envoyer
DIALTONE_MESSAGE_INPUT_IMAGE_PICKER_BUTTON_ARIA_LABEL = Joindre une image
DIALTONE_MESSAGE_INPUT_EMOJI_PICKER_BUTTON_ARIA_LABEL = Sélectionner un emoji
DIALTONE_MESSAGE_INPUT_CANCEL_BUTTON_ARIA_LABEL = Annuler
DIALTONE_MESSAGE_INPUT_BOLD_BUTTON_LABEL =
    .aria-label = Mettre en gras le texte sélectionné
    .tooltip-text = Gras
DIALTONE_MESSAGE_INPUT_ITALIC_BUTTON_LABEL =
    .aria-label = Mettre en italique le texte sélectionné
    .tooltip-text = Italique
DIALTONE_MESSAGE_INPUT_STRIKETHROUGH_BUTTON_LABEL =
    .aria-label = Barrer le texte sélectionné
    .tooltip-text = Barré
DIALTONE_MESSAGE_INPUT_BULLET_LIST_BUTTON_LABEL =
    .aria-label = Créez ou modifiez une liste à puces sur le texte sélectionné
    .tooltip-text = Liste à puces
DIALTONE_MESSAGE_INPUT_ORDERED_LIST_BUTTON_LABEL =
    .aria-label = Créer ou modifier une liste numérotée sur le texte sélectionné
    .tooltip-text = Liste numérotée
DIALTONE_MESSAGE_INPUT_BLOCK_QUOTE_BUTTON_LABEL =
    .aria-label = Créer ou modifier un bloc de citation sur le texte sélectionné
    .tooltip-text = Bloc de citation
DIALTONE_MESSAGE_INPUT_CODE_BUTTON_LABEL =
    .aria-label = Créer ou modifier un code sur le texte sélectionné
    .tooltip-text = Code
DIALTONE_MESSAGE_INPUT_CODE_BLOCK_BUTTON_LABEL =
    .aria-label = Créer ou modifier un bloc de code sur le texte sélectionné
    .tooltip-text = Bloc de code
DIALTONE_MESSAGE_INPUT_LINK_BUTTON_LABEL =
    .aria-label = Créer ou modifier un lien sur le texte sélectionné
    .tooltip-text = Lien
DIALTONE_MESSAGE_INPUT_LINK_DIALOG_TITLE = Ajouter un lien
DIALTONE_MESSAGE_INPUT_LINK_TEXT_LABEL = Texte à afficher (facultatif)
DIALTONE_MESSAGE_INPUT_LINK_LINK_LABEL = Lien
DIALTONE_MESSAGE_INPUT_LINK_LINK_PLACEHOLDER = par exemple : https://www.dialpad.com
DIALTONE_MESSAGE_INPUT_LINK_REMOVE_LABEL = Supprimer
DIALTONE_MESSAGE_INPUT_LINK_CANCEL_LABEL = Annuler
DIALTONE_MESSAGE_INPUT_LINK_CONFIRM_LABEL = Terminé
DIALTONE_PAGINATION_FIRST_PAGE = Prénom
DIALTONE_PAGINATION_PREVIOUS_PAGE = Page précédente
DIALTONE_PAGINATION_NEXT_PAGE = Page suivante
DIALTONE_PAGINATION_LAST_PAGE = Dernière page
DIALTONE_PAGINATION_PAGE_NUMBER = Page numéro { $page }
DIALTONE_RICH_TEXT_EDITOR_EDIT_BUTTON_LABEL = Modifier
DIALTONE_RICH_TEXT_EDITOR_OPEN_LINK_BUTTON_LABEL = Ouvrir le lien
DIALTONE_RICH_TEXT_EDITOR_REMOVE_BUTTON_LABEL = Supprimer
DIALTONE_SETTINGS_MENU_DEFAULT_BUTTON_LABEL = Paramètres
DIALTONE_SETTINGS_MENU_UPDATE_BUTTON_LABEL = Mettre à jour
DIALTONE_UNREAD_PILL_MENTIONS_TEXT = Mentions non lues
DIALTONE_UNREAD_PILL_MESSAGES_TEXT = Messages non lus
# Storybook only
STORYBOOK_LANGUAGE_ENGLISH = Anglais
STORYBOOK_LANGUAGE_CHINESE = Chinois
STORYBOOK_LANGUAGE_DUTCH = Néerlandais
STORYBOOK_LANGUAGE_FRENCH = Français
STORYBOOK_LANGUAGE_GERMAN = Allemand
STORYBOOK_LANGUAGE_ITALIAN = Italien
STORYBOOK_LANGUAGE_JAPANESE = Japonais
STORYBOOK_LANGUAGE_PORTUGUESE = Portugais
STORYBOOK_LANGUAGE_RUSSIAN = Russe
STORYBOOK_LANGUAGE_SPANISH = Espagnol
STORYBOOK_SET_LANGUAGE = Définir la langue
