# Dialtone
DIALTONE_CLOSE_BUTTON = クリックして閉じる
DIALTONE_BREADCRUMBS_ARIA_LABEL = ブレッドクラム
DIALTONE_LOADING = 読み込んでいます
DIALTONE_UNREAD_MESSAGE_COUNT_TEXT =
    { $unreadCount ->
        [0] 未読メッセージはありません
        [1] 1件の未読メッセージ
       *[other] { $unreadCount }件の未読メッセージ
    }
DIALTONE_UNREAD_MENTION_COUNT_TEXT =
    { $unreadCount ->
        [0] 未読メンションはありません
        [1] 1件の未読メンション
       *[other] { $unreadCount }件の未読メンション
    }
DIALTONE_TYPING_TEXT = 入力中
DIALTONE_ATTACHMENT_CAROUSEL_CLICK_TO_OPEN_ARIA_LABEL = クリックして開く
DIALTONE_ATTACHMENT_CAROUSEL_PROGRESS_BAR_ARIA_LABEL = アップロードしています...
DIALTONE_ATTACHMENT_CAROUSEL_LEFT_ARROW_ARIA_LABEL = 前へ
DIALTONE_ATTACHMENT_CAROUSEL_RIGHT_ARROW_ARIA_LABEL = 次へ
DIALTONE_CALLBAR_BUTTON_WITH_DROPDOWN_ARROW_BUTTON_ARIA_LABEL = ドロップダウンを開く
DIALTONE_CALLBAR_BUTTON_WITH_POPOVER_ARROW_BUTTON_ARIA_LABEL = ポップオーバーを開く
DIALTONE_CONTACT_CENTERS_ROW_MENU_BUTTON_LABEL = メニューを開く
DIALTONE_DATEPICKER_PREVIOUS_MONTH = 前月
DIALTONE_DATEPICKER_NEXT_MONTH = 来月
DIALTONE_DATEPICKER_PREVIOUS_YEAR = 前年
DIALTONE_DATEPICKER_NEXT_YEAR = 来年
DIALTONE_DATEPICKER_SELECT_DAY = 曜日を選択
DIALTONE_DATEPICKER_CHANGE_TO = 次に変更 :
DIALTONE_EDITOR_CONFIRM_SET_LINK_BUTTON =
    .title = 確認
    .aria-label = 設定リンクを確定
DIALTONE_EDITOR_REMOVE_LINK_BUTTON =
    .title = 削除
    .aria-label = リンクを削除
DIALTONE_EDITOR_CANCEL_SET_LINK_BUTTON =
    .title = キャンセル
    .aria-label = 設定リンクをキャンセル
DIALTONE_EDITOR_QUICK_REPLY_BUTTON_LABEL = クイック返信
DIALTONE_EDITOR_BOLD_BUTTON_LABEL = 太字
DIALTONE_EDITOR_ITALICS_BUTTON_LABEL = 斜体
DIALTONE_EDITOR_UNDERLINE_BUTTON_LABEL = 下線
DIALTONE_EDITOR_STRIKE_BUTTON_LABEL = 取り消し線
DIALTONE_EDITOR_ALIGN_LEFT_BUTTON_LABEL = 左揃え
DIALTONE_EDITOR_ALIGN_CENTER_BUTTON_LABEL = 中央揃え
DIALTONE_EDITOR_ALIGN_RIGHT_BUTTON_LABEL = 右揃え
DIALTONE_EDITOR_ALIGN_JUSTIFY_BUTTON_LABEL = 両端揃え
DIALTONE_EDITOR_BULLET_LIST_BUTTON_LABEL = 箇条書きリスト
DIALTONE_EDITOR_ORDERED_LIST_BUTTON_LABEL = 番号付きリスト
DIALTONE_EDITOR_QUOTE_BUTTON_LABEL = 引用
DIALTONE_EDITOR_CODE_BUTTON_LABEL = コード
DIALTONE_EDITOR_IMAGE_BUTTON_LABEL = 画像
DIALTONE_EDITOR_LINK_BUTTON_LABEL = リンク
DIALTONE_EDITOR_ADD_LINK_BUTTON =
    .title = リンクを追加
    .aria-label = リンクを追加するための入力フィールド
DIALTONE_EMOJI_ROW_REACTION_LABEL =
    { $reactionCount ->
       *[other]
            { $selected ->
               *[false] { $reactionCount }人が { $reaction } で反応しました。
                [true] 自分を含む{ $reactionCount }人が { $reaction } で反応しました。
            }
    }
DIALTONE_EMOJI_PICKER_ADD_EMOJI_LABEL = 絵文字を追加
DIALTONE_EMOJI_PICKER_SEARCH_NO_RESULTS_LABEL = 見つかりません
DIALTONE_EMOJI_PICKER_SEARCH_RESULTS_LABEL = 検索結果
DIALTONE_EMOJI_PICKER_SEARCH_PLACEHOLDER_LABEL = 検索...
DIALTONE_EMOJI_PICKER_SKIN_SELECTOR_BUTTON_TOOLTIP_LABEL = デフォルトの肌の色を変更
DIALTONE_EMOJI_PICKER_TABSET_RECENTLY_USED_LABEL = 最近使用
DIALTONE_EMOJI_PICKER_TABSET_SMILEYS_AND_PEOPLE_LABEL = スマイリー＆人物
DIALTONE_EMOJI_PICKER_TABSET_NATURE_LABEL = 自然
DIALTONE_EMOJI_PICKER_TABSET_FOOD_LABEL = 食べ物
DIALTONE_EMOJI_PICKER_TABSET_ACTIVITY_LABEL = アクティビティ
DIALTONE_EMOJI_PICKER_TABSET_TRAVEL_LABEL = 旅行
DIALTONE_EMOJI_PICKER_TABSET_OBJECTS_LABEL = オブジェクト
DIALTONE_EMOJI_PICKER_TABSET_SYMBOLS_LABEL = 記号
DIALTONE_EMOJI_PICKER_TABSET_FLAGS_LABEL = フラグ
DIALTONE_EMOJI_PICKER_TABSET_CUSTOM_LABEL = カスタム
DIALTONE_FEED_ITEM_PILL_ARIA_LABEL = クリックして展開
DIALTONE_GENERAL_ROW_ACTIVE_VOICE_CHAT_TEXT = 進行中の音声チャット
DIALTONE_GENERAL_ROW_CALL_BUTTON_TOOLTIP = 発信
DIALTONE_GENERAL_ROW_DND_TEXT_TOOLTIP = プライバシーモード
DIALTONE_GROUP_ROW_GROUP_COUNT_TEXT =
    { $count ->
        [1] 1ユーザー
       *[other] { $count } ユーザー
    }
DIALTONE_IVR_NODE_MENU_BUTTON_ARIA_LABEL = メニューを開く
DIALTONE_IVR_NODE_PROMPTMENU_ARIA_LABEL = プロンプトメニューノード
DIALTONE_IVR_NODE_PROMPTCOLLECT_ARIA_LABEL = プロンプト収集ノード
DIALTONE_IVR_NODE_PROMPTPLAY_ARIA_LABEL = プロンプト再生ノード
DIALTONE_IVR_NODE_GOTOEXPERT_ARIA_LABEL = Expertノードへ移動
DIALTONE_IVR_NODE_BRANCH_ARIA_LABEL = ブランチノード
DIALTONE_IVR_NODE_GOTO_ARIA_LABEL = ノードへ
DIALTONE_IVR_NODE_ASSIGN_ARIA_LABEL = ノードを割り当て
DIALTONE_IVR_NODE_CUSTOMERDATA_ARIA_LABEL = 顧客データノード
DIALTONE_IVR_NODE_TRANSFER_ARIA_LABEL = 転送ノード
DIALTONE_IVR_NODE_HANGUP_ARIA_LABEL = 通話終了ノード
DIALTONE_MESSAGE_INPUT_SEND_BUTTON_ARIA_LABEL = 送信
DIALTONE_MESSAGE_INPUT_IMAGE_PICKER_BUTTON_ARIA_LABEL = 画像を添付
DIALTONE_MESSAGE_INPUT_EMOJI_PICKER_BUTTON_ARIA_LABEL = 絵文字を選択
DIALTONE_MESSAGE_INPUT_CANCEL_BUTTON_ARIA_LABEL = キャンセル
DIALTONE_MESSAGE_INPUT_BOLD_BUTTON_LABEL =
    .aria-label = 選択したテキストの太字を切り替え
    .tooltip-text = 太字
DIALTONE_MESSAGE_INPUT_ITALIC_BUTTON_LABEL =
    .aria-label = 選択したテキストの斜体を切り替え
    .tooltip-text = 斜体
DIALTONE_MESSAGE_INPUT_STRIKETHROUGH_BUTTON_LABEL =
    .aria-label = 選択したテキストの取り消し線を切り替え
    .tooltip-text = 取り消し線
DIALTONE_MESSAGE_INPUT_BULLET_LIST_BUTTON_LABEL =
    .aria-label = 選択したテキストの箇条書きを作成・編集
    .tooltip-text = 箇条書きリスト
DIALTONE_MESSAGE_INPUT_ORDERED_LIST_BUTTON_LABEL =
    .aria-label = 選択したテキストの番号付きリストを作成・編集
    .tooltip-text = 番号付きリスト
DIALTONE_MESSAGE_INPUT_BLOCK_QUOTE_BUTTON_LABEL =
    .aria-label = 選択したテキストの引用ブロックを作成・編集
    .tooltip-text = 引用ブロック
DIALTONE_MESSAGE_INPUT_CODE_BUTTON_LABEL =
    .aria-label = 選択したテキストのコードを作成・編集
    .tooltip-text = コード
DIALTONE_MESSAGE_INPUT_CODE_BLOCK_BUTTON_LABEL =
    .aria-label = 選択したテキストのコードブロックを作成・編集
    .tooltip-text = コードブロック
DIALTONE_MESSAGE_INPUT_LINK_BUTTON_LABEL =
    .aria-label = 選択したテキストのリンクを作成・編集
    .tooltip-text = リンク
DIALTONE_MESSAGE_INPUT_LINK_DIALOG_TITLE = リンクを追加
DIALTONE_MESSAGE_INPUT_LINK_TEXT_LABEL = 表示するテキスト (任意)
DIALTONE_MESSAGE_INPUT_LINK_LINK_LABEL = リンク
DIALTONE_MESSAGE_INPUT_LINK_LINK_PLACEHOLDER = 例 : https://www.dialpad.com
DIALTONE_MESSAGE_INPUT_LINK_REMOVE_LABEL = 削除
DIALTONE_MESSAGE_INPUT_LINK_CANCEL_LABEL = キャンセル
DIALTONE_MESSAGE_INPUT_LINK_CONFIRM_LABEL = 完了
DIALTONE_PAGINATION_FIRST_PAGE = 最初のページ
DIALTONE_PAGINATION_PREVIOUS_PAGE = 前のページ
DIALTONE_PAGINATION_NEXT_PAGE = 次のページ
DIALTONE_PAGINATION_LAST_PAGE = 最後のページ
DIALTONE_PAGINATION_PAGE_NUMBER = ページ番号 { $page }
DIALTONE_RICH_TEXT_EDITOR_EDIT_BUTTON_LABEL = 編集
DIALTONE_RICH_TEXT_EDITOR_OPEN_LINK_BUTTON_LABEL = リンクを開く
DIALTONE_RICH_TEXT_EDITOR_REMOVE_BUTTON_LABEL = 削除
DIALTONE_SETTINGS_MENU_DEFAULT_BUTTON_LABEL = 設定
DIALTONE_SETTINGS_MENU_UPDATE_BUTTON_LABEL = アップデート
DIALTONE_UNREAD_PILL_MENTIONS_TEXT = 未読のメンション
DIALTONE_UNREAD_PILL_MESSAGES_TEXT = 未読メッセージ
# Storybook only
STORYBOOK_LANGUAGE_ENGLISH = 英語
STORYBOOK_LANGUAGE_CHINESE = 中国語
STORYBOOK_LANGUAGE_DUTCH = オランダ語
STORYBOOK_LANGUAGE_FRENCH = フランス語
STORYBOOK_LANGUAGE_GERMAN = ドイツ語
STORYBOOK_LANGUAGE_ITALIAN = イタリア語
STORYBOOK_LANGUAGE_JAPANESE = 日本語
STORYBOOK_LANGUAGE_PORTUGUESE = ポルトガル語
STORYBOOK_LANGUAGE_RUSSIAN = ロシア語
STORYBOOK_LANGUAGE_SPANISH = スペイン語
STORYBOOK_SET_LANGUAGE = 言語を設定
