# Dialtone
DIALTONE_CLOSE_BUTTON = Klik om te sluiten
DIALTONE_BREADCRUMBS_ARIA_LABEL = Breadcrumbs
DIALTONE_LOADING = Laden
DIALTONE_UNREAD_MESSAGE_COUNT_TEXT =
    { $unreadCount ->
        [0] Geen ongelezen berichten
        [1] 1 ongelezen bericht
       *[other] { $unreadCount } ongelezen berichten
    }
DIALTONE_UNREAD_MENTION_COUNT_TEXT =
    { $unreadCount ->
        [0] Geen ongelezen vermeldingen
        [1] 1 ongelezen vermelding
       *[other] { $unreadCount } ongelezen vermeldingen
    }
DIALTONE_TYPING_TEXT = Typen
DIALTONE_ATTACHMENT_CAROUSEL_CLICK_TO_OPEN_ARIA_LABEL = Klik om te openen
DIALTONE_ATTACHMENT_CAROUSEL_PROGRESS_BAR_ARIA_LABEL = Uploaden
DIALTONE_ATTACHMENT_CAROUSEL_LEFT_ARROW_ARIA_LABEL = vorige
DIALTONE_ATTACHMENT_CAROUSEL_RIGHT_ARROW_ARIA_LABEL = Volgende
DIALTONE_CALLBAR_BUTTON_WITH_DROPDOWN_ARROW_BUTTON_ARIA_LABEL = Vervolgkeuzelijst openen
DIALTONE_CALLBAR_BUTTON_WITH_POPOVER_ARROW_BUTTON_ARIA_LABEL = Popover openen
DIALTONE_CONTACT_CENTERS_ROW_MENU_BUTTON_LABEL = Menu openen
DIALTONE_DATEPICKER_PREVIOUS_MONTH = Vorige maand
DIALTONE_DATEPICKER_NEXT_MONTH = volgende maand
DIALTONE_DATEPICKER_PREVIOUS_YEAR = Vorig jaar
DIALTONE_DATEPICKER_NEXT_YEAR = volgend jaar
DIALTONE_DATEPICKER_SELECT_DAY = Dag selecteren
DIALTONE_DATEPICKER_CHANGE_TO = Wijzigen in
DIALTONE_EDITOR_CONFIRM_SET_LINK_BUTTON =
    .title = Bevestigen
    .aria-label = Ingestelde link bevestigen
DIALTONE_EDITOR_REMOVE_LINK_BUTTON =
    .title = Verwijderen
    .aria-label = Link verwijderen
DIALTONE_EDITOR_CANCEL_SET_LINK_BUTTON =
    .title = Annuleren
    .aria-label = Ingestelde link annuleren
DIALTONE_EDITOR_QUICK_REPLY_BUTTON_LABEL = Sjabloon
DIALTONE_EDITOR_BOLD_BUTTON_LABEL = Vet
DIALTONE_EDITOR_ITALICS_BUTTON_LABEL = Cursief
DIALTONE_EDITOR_UNDERLINE_BUTTON_LABEL = Onderstrepen
DIALTONE_EDITOR_STRIKE_BUTTON_LABEL = Doorhalen
DIALTONE_EDITOR_ALIGN_LEFT_BUTTON_LABEL = Links uitlijnen
DIALTONE_EDITOR_ALIGN_CENTER_BUTTON_LABEL = Centreren
DIALTONE_EDITOR_ALIGN_RIGHT_BUTTON_LABEL = Rechts uitlijnen
DIALTONE_EDITOR_ALIGN_JUSTIFY_BUTTON_LABEL = Uitvullen
DIALTONE_EDITOR_BULLET_LIST_BUTTON_LABEL = Lijst met opsommingstekens
DIALTONE_EDITOR_ORDERED_LIST_BUTTON_LABEL = Lijst op volgorde
DIALTONE_EDITOR_QUOTE_BUTTON_LABEL = Citaat
DIALTONE_EDITOR_CODE_BUTTON_LABEL = Code
DIALTONE_EDITOR_IMAGE_BUTTON_LABEL = Afbeelding
DIALTONE_EDITOR_LINK_BUTTON_LABEL = Link
DIALTONE_EDITOR_ADD_LINK_BUTTON =
    .title = Link toevoegen
    .aria-label = Invoerveld om link toe te voegen
DIALTONE_EMOJI_PICKER_ADD_EMOJI_LABEL = Emoji toevoegen
DIALTONE_EMOJI_PICKER_SEARCH_NO_RESULTS_LABEL = Geen resultaten
DIALTONE_EMOJI_PICKER_SEARCH_RESULTS_LABEL = Zoekresultaten
DIALTONE_EMOJI_PICKER_SEARCH_PLACEHOLDER_LABEL = Zoeken...
DIALTONE_EMOJI_PICKER_SKIN_SELECTOR_BUTTON_TOOLTIP_LABEL = Standaardhuidskleur wijzigen
DIALTONE_EMOJI_PICKER_TABSET_RECENTLY_USED_LABEL = Meest recent gebruikt
DIALTONE_EMOJI_PICKER_TABSET_SMILEYS_AND_PEOPLE_LABEL = Smileys en mensen
DIALTONE_EMOJI_PICKER_TABSET_NATURE_LABEL = Natuur
DIALTONE_EMOJI_PICKER_TABSET_FOOD_LABEL = Voedsel
DIALTONE_EMOJI_PICKER_TABSET_ACTIVITY_LABEL = Activiteit
DIALTONE_EMOJI_PICKER_TABSET_TRAVEL_LABEL = Reizen
DIALTONE_EMOJI_PICKER_TABSET_OBJECTS_LABEL = Voorwerpen
DIALTONE_EMOJI_PICKER_TABSET_SYMBOLS_LABEL = Symbolen
DIALTONE_EMOJI_PICKER_TABSET_FLAGS_LABEL = Vlaggen
DIALTONE_EMOJI_PICKER_TABSET_CUSTOM_LABEL = Op maat
DIALTONE_FEED_ITEM_PILL_ARIA_LABEL = Klik om uit te vouwen
DIALTONE_GENERAL_ROW_ACTIVE_VOICE_CHAT_TEXT = Actieve voicechat
DIALTONE_GENERAL_ROW_CALL_BUTTON_TOOLTIP = Bel
DIALTONE_GENERAL_ROW_DND_TEXT_TOOLTIP = Niet storen
DIALTONE_GROUP_ROW_GROUP_COUNT_TEXT =
    { $count ->
        [1] 1 gebruiker
       *[other] { $count } gebruikers
    }
DIALTONE_IVR_NODE_MENU_BUTTON_ARIA_LABEL = Menu openen
DIALTONE_IVR_NODE_PROMPTMENU_ARIA_LABEL = knooppunt promptmenu
DIALTONE_IVR_NODE_PROMPTCOLLECT_ARIA_LABEL = knooppunt prompt verzamelen
DIALTONE_IVR_NODE_PROMPTPLAY_ARIA_LABEL = knooppunt prompt afspelen
DIALTONE_IVR_NODE_GOTOEXPERT_ARIA_LABEL = knooppunt naar expert
DIALTONE_IVR_NODE_BRANCH_ARIA_LABEL = knooppunt vertakking
DIALTONE_IVR_NODE_GOTO_ARIA_LABEL = knooppunt ga naar
DIALTONE_IVR_NODE_ASSIGN_ARIA_LABEL = knooppunt toewijzen
DIALTONE_IVR_NODE_CUSTOMERDATA_ARIA_LABEL = knooppunt klantgegevens
DIALTONE_IVR_NODE_TRANSFER_ARIA_LABEL = knooppunt overdracht
DIALTONE_IVR_NODE_HANGUP_ARIA_LABEL = knooppunt ophangen
DIALTONE_MESSAGE_INPUT_SEND_BUTTON_ARIA_LABEL = VERZENDEN
DIALTONE_MESSAGE_INPUT_IMAGE_PICKER_BUTTON_ARIA_LABEL = Afbeelding bijvoegen
DIALTONE_MESSAGE_INPUT_EMOJI_PICKER_BUTTON_ARIA_LABEL = Emoji selecteren
DIALTONE_MESSAGE_INPUT_CANCEL_BUTTON_ARIA_LABEL = Annuleren
DIALTONE_MESSAGE_INPUT_BOLD_BUTTON_LABEL =
    .aria-label = Vet in- of uitschakelen voor geselecteerde tekst
    .tooltip-text = Vet
DIALTONE_MESSAGE_INPUT_ITALIC_BUTTON_LABEL =
    .aria-label = Cursief in- of uitschakelen voor geselecteerde tekst
    .tooltip-text = Cursief
DIALTONE_MESSAGE_INPUT_STRIKETHROUGH_BUTTON_LABEL =
    .aria-label = Doorhalen in- of uitschakelen voor geselecteerde tekst
    .tooltip-text = Doorhalen
DIALTONE_MESSAGE_INPUT_BULLET_LIST_BUTTON_LABEL =
    .aria-label = Lijst met opsommingstekens maken of bewerken voor geselecteerde tekst
    .tooltip-text = Lijst met opsommingstekens
DIALTONE_MESSAGE_INPUT_ORDERED_LIST_BUTTON_LABEL =
    .aria-label = Lijst op volgorde maken of bewerken voor geselecteerde tekst
    .tooltip-text = Lijst op volgorde
DIALTONE_MESSAGE_INPUT_BLOCK_QUOTE_BUTTON_LABEL =
    .aria-label = Blokcitaat maken of bewerken voor geselecteerde tekst
    .tooltip-text = Blokcitaat
DIALTONE_MESSAGE_INPUT_CODE_BUTTON_LABEL =
    .aria-label = Code maken of bewerken voor geselecteerde tekst
    .tooltip-text = Code
DIALTONE_MESSAGE_INPUT_CODE_BLOCK_BUTTON_LABEL =
    .aria-label = Codeblok maken of bewerken voor geselecteerde tekst
    .tooltip-text = Codeblok
DIALTONE_MESSAGE_INPUT_LINK_BUTTON_LABEL =
    .aria-label = Link maken of bewerken voor geselecteerde tekst
    .tooltip-text = Link
DIALTONE_MESSAGE_INPUT_LINK_DIALOG_TITLE = Link toevoegen
DIALTONE_MESSAGE_INPUT_LINK_TEXT_LABEL = Tekst om weer te geven (optioneel)
DIALTONE_MESSAGE_INPUT_LINK_LINK_LABEL = Link
DIALTONE_MESSAGE_INPUT_LINK_LINK_PLACEHOLDER = bijv. https://www.dialpad.com
DIALTONE_MESSAGE_INPUT_LINK_REMOVE_LABEL = Verwijderen
DIALTONE_MESSAGE_INPUT_LINK_CANCEL_LABEL = Annuleren
DIALTONE_MESSAGE_INPUT_LINK_CONFIRM_LABEL = Klaar
DIALTONE_PAGINATION_FIRST_PAGE = Eerste pagina
DIALTONE_PAGINATION_PREVIOUS_PAGE = Vorige pagina
DIALTONE_PAGINATION_NEXT_PAGE = Volgende pagina
DIALTONE_PAGINATION_LAST_PAGE = Laatste pagina
DIALTONE_PAGINATION_PAGE_NUMBER = Paginanummer { $page }
DIALTONE_RICH_TEXT_EDITOR_EDIT_BUTTON_LABEL = Bewerken
DIALTONE_RICH_TEXT_EDITOR_OPEN_LINK_BUTTON_LABEL = Link openen
DIALTONE_RICH_TEXT_EDITOR_REMOVE_BUTTON_LABEL = Verwijderen
DIALTONE_SETTINGS_MENU_DEFAULT_BUTTON_LABEL = Instellingen
DIALTONE_SETTINGS_MENU_UPDATE_BUTTON_LABEL = Bijwerken
DIALTONE_UNREAD_PILL_MENTIONS_TEXT = Ongelezen vermeldingen
DIALTONE_UNREAD_PILL_MESSAGES_TEXT = Ongelezen berichten
# Storybook only
STORYBOOK_LANGUAGE_ENGLISH = Engels
STORYBOOK_LANGUAGE_CHINESE = Chinees
STORYBOOK_LANGUAGE_DUTCH = Nederlands
STORYBOOK_LANGUAGE_FRENCH = Frans
STORYBOOK_LANGUAGE_GERMAN = Duits
STORYBOOK_LANGUAGE_ITALIAN = Italiaans
STORYBOOK_LANGUAGE_JAPANESE = Japans
STORYBOOK_LANGUAGE_PORTUGUESE = Portugees
STORYBOOK_LANGUAGE_RUSSIAN = Russisch
STORYBOOK_LANGUAGE_SPANISH = Spaans
STORYBOOK_SET_LANGUAGE = Taal instellen
