# Dialtone
DIALTONE_CLOSE_BUTTON = 点击关闭
DIALTONE_BREADCRUMBS_ARIA_LABEL = 面包屑导航
DIALTONE_LOADING = 正在加载
DIALTONE_UNREAD_MESSAGE_COUNT_TEXT =
  { $unreadCount ->
  [0] 没有未读消息
  [1] 1 条未读消息
  *[other] { $unreadCount } 条未读消息
      }
DIALTONE_UNREAD_MENTION_COUNT_TEXT =
  { $unreadCount ->
  [0] 没有未读提及
  [1] 1 条未读提及
  *[other] { $unreadCount } 条未读提及
      }
DIALTONE_TYPING_TEXT = 正在打字
DIALTONE_ATTACHMENT_CAROUSEL_CLICK_TO_OPEN_ARIA_LABEL = 点击打开
DIALTONE_ATTACHMENT_CAROUSEL_PROGRESS_BAR_ARIA_LABEL = 上传
DIALTONE_ATTACHMENT_CAROUSEL_LEFT_ARROW_ARIA_LABEL = 上一步
DIALTONE_ATTACHMENT_CAROUSEL_RIGHT_ARROW_ARIA_LABEL = 下一步
DIALTONE_CALLBAR_BUTTON_WITH_DROPDOWN_ARROW_BUTTON_ARIA_LABEL = 打开下拉菜单
DIALTONE_CALLBAR_BUTTON_WITH_POPOVER_ARROW_BUTTON_ARIA_LABEL = 打开弹出窗口
DIALTONE_CONTACT_CENTERS_ROW_MENU_BUTTON_LABEL = 打开菜单
DIALTONE_DATEPICKER_PREVIOUS_MONTH = 上个月
DIALTONE_DATEPICKER_NEXT_MONTH = 下个月
DIALTONE_DATEPICKER_PREVIOUS_YEAR = 上一年
DIALTONE_DATEPICKER_NEXT_YEAR = 明年
DIALTONE_DATEPICKER_SELECT_DAY = 选择日期
DIALTONE_DATEPICKER_CHANGE_TO = 更改为
DIALTONE_EDITOR_CONFIRM_SET_LINK_BUTTON =
  .title = 确认
  .aria-label = 确认设置链接
DIALTONE_EDITOR_REMOVE_LINK_BUTTON =
  .title = 移除
  .aria-label = 删除链接
DIALTONE_EDITOR_CANCEL_SET_LINK_BUTTON =
  .title = 取消
  .aria-label = 取消设置链接
DIALTONE_EDITOR_QUICK_REPLY_BUTTON_LABEL = 模板
DIALTONE_EDITOR_BOLD_BUTTON_LABEL = 粗体
DIALTONE_EDITOR_ITALICS_BUTTON_LABEL = 斜体
DIALTONE_EDITOR_UNDERLINE_BUTTON_LABEL = 下划线
DIALTONE_EDITOR_STRIKE_BUTTON_LABEL = 删除线
DIALTONE_EDITOR_ALIGN_LEFT_BUTTON_LABEL = 左对齐
DIALTONE_EDITOR_ALIGN_CENTER_BUTTON_LABEL = 居中对齐
DIALTONE_EDITOR_ALIGN_RIGHT_BUTTON_LABEL = 右对齐
DIALTONE_EDITOR_ALIGN_JUSTIFY_BUTTON_LABEL = 对齐
DIALTONE_EDITOR_BULLET_LIST_BUTTON_LABEL = 项目符号列表
DIALTONE_EDITOR_ORDERED_LIST_BUTTON_LABEL = 有序列表
DIALTONE_EDITOR_QUOTE_BUTTON_LABEL = 引用
DIALTONE_EDITOR_CODE_BUTTON_LABEL = 代码
DIALTONE_EDITOR_IMAGE_BUTTON_LABEL = 图像
DIALTONE_EDITOR_LINK_BUTTON_LABEL = 链接
DIALTONE_EDITOR_ADD_LINK_BUTTON =
  .title = 添加链接
  .aria-label = 添加链接的输入字段
DIALTONE_EMOJI_ROW_REACTION_LABEL =
  { $personCount ->
  *[other] 使用了 { $reaction } 作为回复
      }
DIALTONE_EMOJI_PICKER_ADD_EMOJI_LABEL = 添加表情符号
DIALTONE_EMOJI_PICKER_SEARCH_NO_RESULTS_LABEL = 没有结果
DIALTONE_EMOJI_PICKER_SEARCH_RESULTS_LABEL = 搜索结果
DIALTONE_EMOJI_PICKER_SEARCH_PLACEHOLDER_LABEL = 搜索……
DIALTONE_EMOJI_PICKER_SKIN_SELECTOR_BUTTON_TOOLTIP_LABEL = 更改默认肤色
DIALTONE_EMOJI_PICKER_TABSET_RECENTLY_USED_LABEL = 最近使用
DIALTONE_EMOJI_PICKER_TABSET_SMILEYS_AND_PEOPLE_LABEL = 笑脸和人物
DIALTONE_EMOJI_PICKER_TABSET_NATURE_LABEL = 自然
DIALTONE_EMOJI_PICKER_TABSET_FOOD_LABEL = 食物
DIALTONE_EMOJI_PICKER_TABSET_ACTIVITY_LABEL = 活动
DIALTONE_EMOJI_PICKER_TABSET_TRAVEL_LABEL = 旅行
DIALTONE_EMOJI_PICKER_TABSET_OBJECTS_LABEL = 对象
DIALTONE_EMOJI_PICKER_TABSET_SYMBOLS_LABEL = 符号
DIALTONE_EMOJI_PICKER_TABSET_FLAGS_LABEL = 旗帜
DIALTONE_EMOJI_PICKER_TABSET_CUSTOM_LABEL = 自定义
DIALTONE_FEED_ITEM_PILL_ARIA_LABEL = 点击展开
DIALTONE_GENERAL_ROW_ACTIVE_VOICE_CHAT_TEXT = 进行语音聊天
DIALTONE_GENERAL_ROW_CALL_BUTTON_TOOLTIP = 呼叫
DIALTONE_GENERAL_ROW_DND_TEXT_TOOLTIP = 请勿打扰
DIALTONE_GROUP_ROW_GROUP_COUNT_TEXT =
  { $count ->
  [1] 1 位用户
  *[other] { $count } 用户
      }
DIALTONE_IVR_NODE_MENU_BUTTON_ARIA_LABEL = 打开菜单
DIALTONE_IVR_NODE_PROMPTMENU_ARIA_LABEL = 提示菜单节点
DIALTONE_IVR_NODE_PROMPTCOLLECT_ARIA_LABEL = 提示收集节点
DIALTONE_IVR_NODE_PROMPTPLAY_ARIA_LABEL = 提示播放节点
DIALTONE_IVR_NODE_GOTOEXPERT_ARIA_LABEL = 前往专家节点
DIALTONE_IVR_NODE_BRANCH_ARIA_LABEL = 分支节点
DIALTONE_IVR_NODE_GOTO_ARIA_LABEL = 转到节点
DIALTONE_IVR_NODE_ASSIGN_ARIA_LABEL = 分配节点
DIALTONE_IVR_NODE_CUSTOMERDATA_ARIA_LABEL = 客户数据节点
DIALTONE_IVR_NODE_TRANSFER_ARIA_LABEL = 传输节点
DIALTONE_IVR_NODE_HANGUP_ARIA_LABEL = 挂断节点
DIALTONE_MESSAGE_INPUT_SEND_BUTTON_ARIA_LABEL = 发送
DIALTONE_MESSAGE_INPUT_IMAGE_PICKER_BUTTON_ARIA_LABEL = 附上图片
DIALTONE_MESSAGE_INPUT_EMOJI_PICKER_BUTTON_ARIA_LABEL = 选择表情符号
DIALTONE_MESSAGE_INPUT_CANCEL_BUTTON_ARIA_LABEL = 取消
DIALTONE_MESSAGE_INPUT_BOLD_BUTTON_LABEL =
  .aria-label = 切换选定文本的粗体
  .tooltip-text = 粗体
DIALTONE_MESSAGE_INPUT_ITALIC_BUTTON_LABEL =
  .aria-label = 切换所选文本的斜体
  .tooltip-text = 斜体
DIALTONE_MESSAGE_INPUT_STRIKETHROUGH_BUTTON_LABEL =
  .aria-label = 切换选定文本的删除线
  .tooltip-text = 删除线
DIALTONE_MESSAGE_INPUT_BULLET_LIST_BUTTON_LABEL =
  .aria-label = 在选定的文本上创建或编辑项目符号列表
  .tooltip-text = 项目符号列表
DIALTONE_MESSAGE_INPUT_ORDERED_LIST_BUTTON_LABEL =
  .aria-label = 创建或编辑选定文本的有序列表
  .tooltip-text = 有序列表
DIALTONE_MESSAGE_INPUT_BLOCK_QUOTE_BUTTON_LABEL =
  .aria-label = 在选定的文本上创建或编辑块引用
  .tooltip-text = 块引用
DIALTONE_MESSAGE_INPUT_CODE_BUTTON_LABEL =
  .aria-label = 在选定的文本上创建或编辑代码
  .tooltip-text = 代码
DIALTONE_MESSAGE_INPUT_CODE_BLOCK_BUTTON_LABEL =
  .aria-label = 在选定的文本上创建或编辑代码块
  .tooltip-text = 代码块
DIALTONE_MESSAGE_INPUT_LINK_BUTTON_LABEL =
  .aria-label = 在选定的文本上创建或编辑链接
  .tooltip-text = 链接
DIALTONE_MESSAGE_INPUT_LINK_DIALOG_TITLE = 添加链接
DIALTONE_MESSAGE_INPUT_LINK_TEXT_LABEL = 显示的文本（可选）
DIALTONE_MESSAGE_INPUT_LINK_LINK_LABEL = 链接
DIALTONE_MESSAGE_INPUT_LINK_LINK_PLACEHOLDER = 例如，https://www.dialpad.com
DIALTONE_MESSAGE_INPUT_LINK_REMOVE_LABEL = 移除
DIALTONE_MESSAGE_INPUT_LINK_CANCEL_LABEL = 取消
DIALTONE_MESSAGE_INPUT_LINK_CONFIRM_LABEL = 完成
DIALTONE_PAGINATION_FIRST_PAGE = 名
DIALTONE_PAGINATION_PREVIOUS_PAGE = 上一页
DIALTONE_PAGINATION_NEXT_PAGE = 下一页
DIALTONE_PAGINATION_LAST_PAGE = 最后一页
DIALTONE_PAGINATION_PAGE_NUMBER = 页码 { $page }
DIALTONE_RICH_TEXT_EDITOR_EDIT_BUTTON_LABEL = 编辑
DIALTONE_RICH_TEXT_EDITOR_OPEN_LINK_BUTTON_LABEL = 打开链接
DIALTONE_RICH_TEXT_EDITOR_REMOVE_BUTTON_LABEL = 移除
DIALTONE_SETTINGS_MENU_DEFAULT_BUTTON_LABEL = 设置
DIALTONE_SETTINGS_MENU_UPDATE_BUTTON_LABEL = 更新
DIALTONE_UNREAD_PILL_MENTIONS_TEXT = 未读提及
DIALTONE_UNREAD_PILL_MESSAGES_TEXT = 未读消息
# Storybook only
STORYBOOK_LANGUAGE_ENGLISH = English
STORYBOOK_LANGUAGE_CHINESE = 中文
STORYBOOK_LANGUAGE_DUTCH = 荷兰语
STORYBOOK_LANGUAGE_FRENCH = 法语
STORYBOOK_LANGUAGE_GERMAN = 德语
STORYBOOK_LANGUAGE_ITALIAN = 意大利语
STORYBOOK_LANGUAGE_JAPANESE = 日语
STORYBOOK_LANGUAGE_PORTUGUESE = 葡萄牙语
STORYBOOK_LANGUAGE_RUSSIAN = 俄语
STORYBOOK_LANGUAGE_SPANISH = 西班牙语
STORYBOOK_SET_LANGUAGE = 设置语言
STORYBOOK_YOU = 您
STORYBOOK_REACTION_NAMES_2 = Olivia Chen、Benjamin Carter、Sophia Rodriguez、William Kim 和 Isabella Garcia
STORYBOOK_REACTION_NAMES_3 = Olivia Chen 和 { STORYBOOK_YOU }
