/**
 * Resizable panel system — types and injection keys.
 *
 * @see dt_resizable.vue — provides all keys
 * @see dt_resizable_panel.vue — consumes panel/layout keys
 * @see dt_resizable_handle.vue — consumes handle/resize keys
 */
import type { InjectionKey, ComputedRef, ComponentInternalInstance } from 'vue';
import type { LayoutResult } from './composables/computeLayout';

// ─── Sizing Types ──────────────────────────────────────────────────────────

/**
 * Resizable panels accept size tokens (numeric strings mapped to pixel values)
 * or percentage values with 'p' suffix (e.g., '50p').
 * parseSizeToPixels() warns for unrecognized values.
 */
export type ResizableSizeValue = string;

// ─── Types ──────────────────────────────────────────────────────────────────

export type ResizableDirection = 'row' | 'column';

export interface ResizablePanelConfig {
  /** Panel identifier. Auto-generated by ResizableGroup if not provided. */
  id: string;
  /** Initial size - size token (e.g., '925') or percentage with 'p' suffix (e.g., '50p') */
  initialSize?: ResizableSizeValue;

  // ─── User Drag Limits (Absolute Boundaries) ───
  /** Hard floor for user dragging. User cannot drag panel smaller than this. */
  userMinSize?: ResizableSizeValue;
  /** Hard ceiling for user dragging. User cannot drag panel larger than this. */
  userMaxSize?: ResizableSizeValue;

  // ─── System Scaling Limits (Operating Range) ───
  /**
   * System scaling floor. System won't compress panel below this during viewport resize.
   * Must be >= userMinSize. Falls back to userMinSize if not specified.
   */
  systemMinSize?: ResizableSizeValue;
  /**
   * System scaling ceiling. System won't expand panel above this during viewport resize.
   * Must be <= userMaxSize. Falls back to userMaxSize if not specified.
   */
  systemMaxSize?: ResizableSizeValue;

  // ─── Auto-Collapse ───
  /**
   * Container width threshold for auto-collapse.
   * When container width drops below this value, panel auto-collapses.
   * This is the container width, not the panel width.
   */
  collapseSize?: ResizableSizeValue;

  // ─── Behavior Flags ───
  /** Whether this panel can be resized by user dragging */
  resizable?: boolean;
  /** Whether this panel can be manually collapsed via UI */
  collapsible?: boolean;
  /** Initial collapsed state */
  collapsed?: boolean;

  // ─── Peek Overlay Configuration ───
  /**
   * Enable peek overlay when panel is collapsed.
   * Shows panel content as a temporary overlay on hover/trigger.
   * Default: false
   */
  peekEnabled?: boolean;
  /**
   * What triggers the peek overlay to appear.
   * - 'hover': Mouse hover over collapsed panel area
   * - 'button': Dedicated button/icon click
   * - 'both': Either hover or button
   * Default: 'hover'
   */
  peekTrigger?: PeekTriggerMode;
  /**
   * Allow peek even when panel was manually collapsed (not auto-collapsed).
   * Default: false (peek only for auto-collapsed panels)
   */
  peekWhenManual?: boolean;
  /**
   * Width of the peek overlay.
   * Uses initialSize if not specified.
   */
  peekWidth?: ResizableSizeValue;
  /**
   * Grace period in milliseconds before hiding peek on mouse leave.
   * Prevents flicker when mouse briefly leaves the peek area.
   * Default: 150
   */
  peekGracePeriod?: number;
}

export interface ResizablePanelState extends ResizablePanelConfig {
  // ─── Core State ───
  /** Current size in pixels (primary storage) */
  pixelSize: number;
  /** Whether this panel is locked at a fixed pixel size */
  locked: boolean;

  // ─── User Drag Constraints (Computed Pixels) ───
  /** Computed pixel value for userMinSize (absolute floor for user dragging) */
  userMinSizePixels?: number;
  /** Computed pixel value for userMaxSize (absolute ceiling for user dragging) */
  userMaxSizePixels?: number;

  // ─── System Scaling Constraints (Computed Pixels) ───
  /** Computed pixel value for systemMinSize (system scaling floor) */
  systemMinSizePixels?: number;
  /** Computed pixel value for systemMaxSize (system scaling ceiling) */
  systemMaxSizePixels?: number;

  // ─── Auto-Collapse State ───
  /** Computed pixel value for collapseSize (container width threshold) */
  collapseSizePixels?: number;
  /** True if panel was auto-collapsed (vs manually collapsed via UI) */
  autoCollapsed?: boolean;

  // ─── Manual Resize Tracking ───
  /**
   * Internal: Stores the user's preferred pixel size when they drag a panel.
   * Used by the drag system to track intent before converting to ratio.
   * Not exposed as a component prop.
   */
  manualTargetSize?: number;
  /**
   * Stores the user's preferred ratio (0–1) when they drag a panel.
   * - undefined: no manual target, panel scales proportionally with viewport
   * - number: panel targets (ratio × containerSize) pixels on each render,
   *   still subject to min/max constraints.
   *
   * Enables correct proportional scaling when the viewport changes.
   * Panel feels "sticky" at the chosen proportion.
   */
  manualTargetRatio?: number;

  // ─── Storage Restoration ───
  /**
   * True if this panel's state was loaded from localStorage on the current
   * initialization pass. Prevents double-restoration when loadFromStorage is
   * called multiple times (e.g. the deferred 100ms retry in useResizableCore).
   */
  restoredFromStorage?: boolean;

  // ─── Peek State ───
  /** Whether the peek overlay is currently visible */
  isPeeking?: boolean;
  /** Computed peek width in pixels (derived from peekWidth or initialSize) */
  peekWidthPixels?: number;
}

export interface ResizableHandleConfig {
  id: string;
  beforePanelId: string;
  afterPanelId: string;
  direction: ResizableDirection;
}

export type ResizableSizeMode = 'percentage' | 'pixels';

/** Trigger modes for peek overlay */
export type PeekTriggerMode = 'hover' | 'button' | 'both';

export interface ResizableGroupConfig {
  direction: ResizableDirection;
  panels: ResizablePanelConfig[];
  storageKey?: string; // Optional localStorage key for persistence
  sizeMode?: ResizableSizeMode; // Whether to use percentage or pixel-based sizing
  limitToParent?: boolean; // Limit resizing to parent viewport bounds
}

export interface ResizableGroupState {
  direction: ResizableDirection;
  panels: ResizablePanelState[];
  containerSize: number; // Total container size in pixels
  isResizing: boolean;
  activeHandleId?: string;
  activeCursorPosition?: number;
}

export interface ResizableEvents {
  'panel-resize': (panelId: string, size: number) => void;
  'panel-collapse': (panelId: string, collapsed: boolean) => void;
  'resize-start': (handleId: string) => void;
  'resize-end': (handleId: string) => void;
  /** Emitted when peek overlay starts showing */
  'panel-peek-start'?: (panelId: string) => void;
  /** Emitted when peek overlay finishes hiding */
  'panel-peek-end'?: (panelId: string) => void;
}

/**
 * Defines collapse behavior for a panel during space constraints.
 * Used to determine which panels collapse first when viewport shrinks.
 */
export interface CollapseRule {
  /** Panel ID this rule applies to */
  panelId: string;
  /** Collapse priority - lower numbers collapse first */
  priority: number;
  /** Optional threshold that triggers collapse (overrides panel's userMinSize) */
  minSizeBeforeCollapse?: ResizableSizeValue;
}

/**
 * Strategy for redistributing space when panels open/close.
 * - 'proportional': Take/give space proportionally from all unlocked panels
 * - 'preserve-manual': Only take from non-manually-resized panels
 */
export type SpaceAllocationStrategy = 'proportional' | 'preserve-manual';

// ─── Defaults ─────────────────────────────────────────────────────────────

/** Default panel size when no initialSize is specified (50% of container). */
export const DEFAULT_PANEL_SIZE = '50p';

/** Minimum panel size in pixels below which a resize is rejected. */
export const MIN_PANEL_SIZE_PX = 10;

// ─── Storage Adapter ───────────────────────────────────────────────────────

/**
 * Interface for pluggable storage backends.
 * Implement this to persist panel layouts to Pinia, Vuex, IndexedDB, etc.
 * The built-in `localStorageAdapter(key)` factory creates a localStorage-backed adapter.
 */
export interface ResizableStorageAdapter {
  /** Persist the current panel layout. */
  save(data: ResizableStoragePanelData[]): void;
  /** Load a previously saved layout. Returns null if nothing is stored. */
  load(): ResizableStoragePanelData[] | null;
  /** Remove all persisted data for this layout. */
  clear(): void;
}

/**
 * Shape of a single panel's persisted data.
 * Intentionally minimal — only what's needed to restore a layout.
 */
export interface ResizableStoragePanelData {
  id: string;
  pixelSize: number;
  locked?: boolean;
  collapsed?: boolean;
  autoCollapsed?: boolean;
  manualTargetRatio?: number;
}

// ─── Injection Keys ─────────────────────────────────────────────────────────
// Typed InjectionKey constants for the resizable panel system.
// All provide/inject between ResizableGroup, ResizablePanel, and ResizableHandle
// must use these keys instead of string literals.

// ─── Reactive State ─────────────────────────────────────────────────────────

/**
 * The full computed layout result from computeLayout().
 * Provided by ResizableGroup, consumed by ResizablePanel (Phase 2+) and
 * ResizableHandle (Phase 3+) to read their positions directly.
 */
export const RESIZABLE_LAYOUT_KEY: InjectionKey<ComputedRef<LayoutResult>> = Symbol('resizable-layout');

export const RESIZABLE_PANELS_KEY: InjectionKey<ComputedRef<ResizablePanelState[]>> = Symbol('resizable-panels');

export const RESIZABLE_DIRECTION_KEY: InjectionKey<ComputedRef<ResizableDirection>> = Symbol('resizable-direction');

export const RESIZABLE_CONTAINER_SIZE_KEY: InjectionKey<ComputedRef<number>> = Symbol('resizable-container-size');

export const RESIZABLE_CONTAINER_ELEMENT_KEY: InjectionKey<ComputedRef<HTMLElement | null>> =
  Symbol('resizable-container-element');

export const RESIZABLE_IS_RESIZING_KEY: InjectionKey<ComputedRef<boolean>> = Symbol('resizable-is-resizing');

export const RESIZABLE_ACTIVE_HANDLE_KEY: InjectionKey<ComputedRef<string | undefined>> =
  Symbol('resizable-active-handle');

export const RESIZABLE_ACTIVE_CURSOR_POSITION_KEY: InjectionKey<ComputedRef<number>> = Symbol(
  'resizable-active-cursor-position'
);

export const RESIZABLE_IS_EDIT_MODE_KEY: InjectionKey<ComputedRef<boolean>> = Symbol('resizable-is-edit-mode');

export const RESIZABLE_IS_INITIALIZING_KEY: InjectionKey<ComputedRef<boolean>> = Symbol('resizable-is-initializing');

// ─── Operations ─────────────────────────────────────────────────────────────

export const RESIZABLE_START_RESIZE_KEY: InjectionKey<(handleId: string) => void> = Symbol('resizable-start-resize');

export const RESIZABLE_RESET_PANELS_KEY: InjectionKey<
  (beforePanelId?: string, afterPanelId?: string, behavior?: 'both' | 'before' | 'after' | 'all') => void
> = Symbol('resizable-reset-panels');

export const RESIZABLE_REGISTER_HANDLE_KEY: InjectionKey<(instance: ComponentInternalInstance | null) => number> =
  Symbol('resizable-register-handle');

export const RESIZABLE_UNREGISTER_HANDLE_KEY: InjectionKey<(instance: ComponentInternalInstance | null) => void> =
  Symbol('resizable-unregister-handle');

export const RESIZABLE_REGISTER_PANEL_KEY: InjectionKey<(config: ResizablePanelConfig) => void> =
  Symbol('resizable-register-panel');

export const RESIZABLE_UNREGISTER_PANEL_KEY: InjectionKey<(id: string) => void> = Symbol('resizable-unregister-panel');

export const RESIZABLE_REGISTER_EDIT_HANDLE_KEY: InjectionKey<(element: HTMLElement) => void> = Symbol(
  'resizable-register-edit-handle'
);

export const RESIZABLE_UNREGISTER_EDIT_HANDLE_KEY: InjectionKey<(element: HTMLElement) => void> = Symbol(
  'resizable-unregister-edit-handle'
);

export const RESIZABLE_SAVE_TO_STORAGE_KEY: InjectionKey<() => void> = Symbol('resizable-save-to-storage');

export const RESIZABLE_COLLAPSE_PANEL_KEY: InjectionKey<(panelId: string, collapsed: boolean) => void> =
  Symbol('resizable-collapse-panel');

export const RESIZABLE_EMIT_PANEL_RESIZE_KEY: InjectionKey<(panelId: string, size: number) => void> =
  Symbol('resizable-emit-panel-resize');

/** i18n message overrides for keyboard announcements, provided by DtResizable */
export const RESIZABLE_MESSAGES_KEY: InjectionKey<Record<string, string>> = Symbol('resizable-messages');
