/**
 * Resizable panel system — types and injection keys.
 *
 * @see resizable.vue — provides all keys
 * @see resizable_panel.vue — consumes panel/layout keys
 * @see resizable_handle.vue — consumes handle/resize keys
 */
import type { InjectionKey, ComputedRef, ComponentInternalInstance } from 'vue';
import type { LayoutResult } from './composables/computeLayout';

// ─── Sizing Types ──────────────────────────────────────────────────────────

/**
 * Resizable panels accept size tokens (numeric strings mapped to pixel values)
 * or percentage values with 'p' suffix (e.g., '50p').
 * parseSizeToPixels() warns for unrecognized values.
 */
export type ResizableSizeValue = string;

// ─── Types ──────────────────────────────────────────────────────────────────

export type ResizableDirection = 'row' | 'column';

export interface ResizablePanelConfig {
  /** Panel identifier. Auto-generated by ResizableGroup if not provided. */
  id: string;
  /** Initial size - size token (e.g., '925') or percentage with 'p' suffix (e.g., '50p') */
  initialSize?: ResizableSizeValue;

  // ─── User Drag Limits (Absolute Boundaries) ───
  /** Hard floor for user dragging. User cannot drag panel smaller than this. */
  userMinSize?: ResizableSizeValue;
  /** Hard ceiling for user dragging. User cannot drag panel larger than this. */
  userMaxSize?: ResizableSizeValue;

  // ─── System Scaling Limits (Operating Range) ───
  /**
   * System scaling floor. System won't compress panel below this during viewport resize.
   * Must be >= userMinSize. Falls back to userMinSize if not specified.
   */
  systemMinSize?: ResizableSizeValue;
  /**
   * System scaling ceiling. System won't expand panel above this during viewport resize.
   * Must be <= userMaxSize. Falls back to userMaxSize if not specified.
   */
  systemMaxSize?: ResizableSizeValue;

  // ─── Auto-Collapse ───
  /**
   * Container width threshold for auto-collapse.
   * When container width drops below this value, panel auto-collapses.
   * This is the container width, not the panel width.
   */
  collapseSize?: ResizableSizeValue;

  // ─── Behavior Flags ───
  /** Whether this panel can be resized by user dragging */
  resizable?: boolean;
  /** Whether this panel can be manually collapsed via UI */
  collapsible?: boolean;
  /** Initial collapsed state */
  collapsed?: boolean;

}

export interface ResizablePanelState extends ResizablePanelConfig {
  // ─── Core State ───
  /** Current size in pixels (primary storage) */
  pixelSize: number;

  // ─── User Drag Constraints (Computed Pixels) ───
  /** Computed pixel value for userMinSize (absolute floor for user dragging) */
  userMinSizePixels?: number;
  /** Computed pixel value for userMaxSize (absolute ceiling for user dragging) */
  userMaxSizePixels?: number;

  // ─── System Scaling Constraints (Computed Pixels) ───
  /** Computed pixel value for systemMinSize (system scaling floor) */
  systemMinSizePixels?: number;
  /** Computed pixel value for systemMaxSize (system scaling ceiling) */
  systemMaxSizePixels?: number;

  // ─── Auto-Collapse State ───
  /** Computed pixel value for collapseSize (container width threshold) */
  collapseSizePixels?: number;
  /** True if panel was auto-collapsed (vs manually collapsed via UI) */
  autoCollapsed?: boolean;

  // ─── Manual Resize Tracking ───
  /**
   * Internal: Stores the user's preferred pixel size when they drag a panel.
   * Used by the drag system to track intent before converting to ratio.
   * Not exposed as a component prop.
   */
  manualTargetSize?: number;
  /**
   * Stores the user's preferred ratio (0–1) when they drag a panel.
   * - undefined: no manual target, panel scales proportionally with viewport
   * - number: panel targets (ratio × containerSize) pixels on each render,
   *   still subject to min/max constraints.
   *
   * Enables correct proportional scaling when the viewport changes.
   * Panel feels "sticky" at the chosen proportion.
   */
  manualTargetRatio?: number;

  // ─── Storage Restoration ───
  /**
   * True if this panel's state was loaded from localStorage on the current
   * initialization pass. Prevents double-restoration when loadFromStorage is
   * called multiple times (e.g. the deferred 100ms retry in useResizableCore).
   */
  restoredFromStorage?: boolean;

}

export interface ResizableHandleConfig {
  id: string;
  beforePanelId: string;
  afterPanelId: string;
  direction: ResizableDirection;
}

export type ResizableSizeMode = 'percentage' | 'pixels';


export interface ResizableGroupConfig {
  direction: ResizableDirection;
  panels: ResizablePanelConfig[];
  storageKey?: string; // Optional localStorage key for persistence
  sizeMode?: ResizableSizeMode; // Whether to use percentage or pixel-based sizing
  limitToParent?: boolean; // Limit resizing to parent viewport bounds
}

export interface ResizableGroupState {
  direction: ResizableDirection;
  panels: ResizablePanelState[];
  containerSize: number; // Total container size in pixels
  isResizing: boolean;
  activeHandleId?: string;
}

export interface ResizableEvents {
  'panel-resize': (panelId: string, size: number) => void;
  'panel-collapse': (panelId: string, collapsed: boolean) => void;
  'resize-start': (handleId: string) => void;
  'resize-end': (handleId: string) => void;
}

/**
 * Defines collapse behavior for a panel during space constraints.
 * Used to determine which panels collapse first when viewport shrinks.
 */
export interface CollapseRule {
  /** Panel ID this rule applies to */
  panelId: string;
  /** Collapse priority - lower numbers collapse first */
  priority: number;
  /** Optional threshold that triggers collapse (overrides panel's userMinSize) */
  minSizeBeforeCollapse?: ResizableSizeValue;
}

/**
// ─── Defaults ─────────────────────────────────────────────────────────────

/** Default panel size when no initialSize is specified (50% of container). */
export const DEFAULT_PANEL_SIZE = '50p';

/** Minimum panel size in pixels below which a resize is rejected. */
export const MIN_PANEL_SIZE_PX = 10;

// ─── Storage Adapter ───────────────────────────────────────────────────────

/**
 * Interface for pluggable storage backends.
 * Implement this to persist panel layouts to Pinia, Vuex, IndexedDB, etc.
 * The built-in `localStorageAdapter(key)` factory creates a localStorage-backed adapter.
 */
export interface ResizableStorageAdapter {
  /** Persist the current panel layout. */
  save(data: ResizableStoragePanelData[]): void;
  /** Load a previously saved layout. Returns null if nothing is stored. */
  load(): ResizableStoragePanelData[] | null;
  /** Remove all persisted data for this layout. */
  clear(): void;
}

/**
 * Shape of a single panel's persisted data.
 * Intentionally minimal — only what's needed to restore a layout.
 */
export interface ResizableStoragePanelData {
  id: string;
  pixelSize: number;
  collapsed?: boolean;
  autoCollapsed?: boolean;
  manualTargetRatio?: number;
}

// ─── Injection Context ──────────────────────────────────────────────────────
// Single context object for provide/inject between ResizableGroup, Panel, Handle.

export interface ResizableContext {
  // Reactive state
  layout: ComputedRef<LayoutResult>;
  panels: ComputedRef<ResizablePanelState[]>;
  panelMap: ComputedRef<Map<string, ResizablePanelState>>;
  direction: ComputedRef<ResizableDirection>;
  containerSize: ComputedRef<number>;
  containerElement: ComputedRef<HTMLElement | null>;
  isResizing: ComputedRef<boolean>;
  activeHandleId: ComputedRef<string | undefined>;
  isInitializing: ComputedRef<boolean>;
  messages: Record<string, string>;

  // Offset (from fixed header/toolbar)
  offsetHandleStyles: ComputedRef<Record<string, string>>;
  offsetContentStyles: ComputedRef<Record<string, string>>;

  // Operations
  startResize: (handleId: string) => void;
  resetPanels: (
    beforePanelId?: string,
    afterPanelId?: string,
    behavior?: 'both' | 'before' | 'after' | 'all',
  ) => void;
  registerHandle: (instance: ComponentInternalInstance | null) => void;
  unregisterHandle: (instance: ComponentInternalInstance | null) => void;
  registerPanel: (config: ResizablePanelConfig) => void;
  unregisterPanel: (id: string) => void;
  saveToStorage: () => void;
  announce: (message: string) => void;
  collapsePanel: (panelId: string, collapsed: boolean) => void;
  emitPanelResize: (panelId: string, size: number) => void;
  commitPanelSize: (panelId: string, pixels: number) => void;
  updateSavedPanel: (panelId: string, updates: Partial<ResizableStoragePanelData>) => void;
}

export const RESIZABLE_CONTEXT_KEY: InjectionKey<ResizableContext> = Symbol('resizable-context');

/**
 * Build a composite handle ID from the before and after panel IDs.
 * Handles use the format "{beforePanelId}:{afterPanelId}" throughout the system.
 */
export function buildHandleId(beforeId: string, afterId: string): string {
  return `${beforeId}:${afterId}`;
}
