name: Linters

on:
  pull_request:
    branches: [ staging, staging-vue3, vue3, production ]
  push:
    branches: [ staging, staging-vue3 ]

jobs:
  linters:

    runs-on: ubuntu-latest

    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      NODE_MODULES_CACHE_VERSION: v3

    steps:
      - name: Check out branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Use Library Cache
        id: library-cache
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules/
            ~/.npm
          key: ${{ format('{0}-dialtone-vue-library-node-modules-{1}-{2}', runner.os, env.NODE_MODULES_CACHE_VERSION, hashFiles(format('package-lock.json'))) }}

      - name: Install dependencies
        if: steps.library-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run code linters
        run: npm run lint:code

      - name: Run docs linters
        run: npm run lint:docs
