#!/usr/bin/env bash
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

# Validate commit message in staging branch
if [[ "$branch" = "staging" ]]; then
  pnpm exec commitlint --edit "$1"
fi
