name: Accessibility Tests

on:
  push:
    branches:
      - staging
      - production

    paths:
      - 'packages/dialtone-vue3/**'

  pull_request:
    types:
      - opened
      - synchronize

    paths:
      - 'packages/dialtone-vue3/**'

env:
  HUSKY: 0

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  dialtone-vue:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Check out branch
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run a11y tests
        run: pnpm nx run dialtone-vue3:test:a11y
