name: Clean Preview

on:
  pull_request_target:
    types: [closed]

jobs:
  clean-preview:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
        if [ -d "deploy-previews/pr-${{ github.event.pull_request.number }}" ]; then 
          rm -rf deploy-previews/pr-${{ github.event.pull_request.number }}
          git add -A
          git commit -m "deploy preview cleanup"
          git push
        else
          echo "No preview was created"
        fi
