name: Lint PR Title

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    branches:
      - staging

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - name: Check out branch
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Lint pull request title
        run: |
          echo "The PR's title should adhere to the commit message convention."
          echo "correct format: <type>(<scope>): <jira> <subject>"
          echo "example: feat: DLT-123 add dialbot icon"
          pnpm commitlint --verbose << EOF
          ${{ github.event.pull_request.title }}
          EOF
