name: Lint PR Title

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    branches:
      - staging

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20 ]

    steps:
      - uses: actions/checkout@v3
        with:
          # we need + 1 commit
          fetch-depth: 2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint pull request title
        run: |
          echo "The PR's title should adhere to the commit message convention."
          echo "correct format: <type>(<scope>): <subject>"
          echo "example: feat: add dialbot icon"
          pnpm commitlint --verbose << EOF
          ${{ github.event.pull_request.title }}
          EOF
