name: Send communications
on:
  workflow_dispatch:
    inputs:
      post_file_name:
        description: 'The post file name'
        required: true
  pull_request:
    paths:
      - 'apps/dialtone-documentation/docs/about/whats-new/posts/*.md'
  push:
    branches:
      - production
    paths:
      - 'apps/dialtone-documentation/docs/about/whats-new/posts/*.md'

env:
  HUSKY: 0

jobs:
  send-email:
    runs-on: ubuntu-latest
    env:
      FROM_MAIL: julio.ortega@dialpad.com
      TO_MAIL: brad-paugh@dialpad.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: 'apps/dialtone-documentation/docs/about/whats-new/posts/*.md'

      - name: Print added markdown files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
        run: |
          echo "One or more blog posts were added."
          echo "List all the files that have been added: $ADDED_FILES"

#      - name: Send email
#        if: false
#        uses: dawidd6/action-send-mail@v3
#        with:
#          server_address: smtp.gmail.com
#          server_port: 465
#          secure: true
#          username: ${{ env.FROM_MAIL }}
#          password: ${{ secrets.MAIL_PASSWORD }}
#          subject: Dialtone updates
#          to: ${{ env.TO_MAIL }}
#          from: ${{ env.FROM_MAIL }}
#          html_body: file://${{ needs.changed-files.outputs.added-files }}
#          bcc: ${{ env.FROM_MAIL }}
#          reply_to: ${{ env.FROM_MAIL }}
#          convert_markdown: true
#          # Optional nodemailer log: true/false
#          nodemailerlog: true
#          # Optional nodemailer debug: true/false
#          # if true log nodemailer will also be set true
#          nodemailerdebug: true
