name: Send communications
on:
  workflow_dispatch:
    inputs:
      post_file_name:
        description: 'The post file name'
        required: true
  pull_request:
    paths:
      - 'apps/dialtone-documentation/docs/about/whats-new/posts/*.md'
  push:
    branches:
      - production
    paths:
      - 'apps/dialtone-documentation/docs/about/whats-new/posts/*.md'

env:
  HUSKY: 0

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      added-posts: ${{ steps.changed-blog-posts.outputs.added_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed blog posts
        id: changed-blog-posts
        uses: tj-actions/changed-files@v42
        with:
          files: 'apps/dialtone-documentation/docs/about/whats-new/posts/*.md'
          json: true
          escape_json: false
      - name: List all changed files
        run: echo '${{ steps.changed-blog-posts.outputs.all_changed_files }}'

  send-email:
    name: Send email
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix:
        files: ${{ fromJSON(needs.changed-files.outputs.added-posts) }}
    env:
      FROM_MAIL: julio.ortega@dialpad.com
      TO_MAIL: julio.ortega@dialpad.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ env.FROM_MAIL }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Dialtone updates
          to: ${{ env.TO_MAIL }}
          from: ${{ env.FROM_MAIL }}
          html_body: file://${{ matrix.files }}
          bcc: ${{ env.FROM_MAIL }}
          reply_to: ${{ env.FROM_MAIL }}
          convert_markdown: false
          # Optional nodemailer log: true/false
          nodemailerlog: true
          # Optional nodemailer debug: true/false
          # if true log nodemailer will also be set true
          nodemailerdebug: true
