name: Send mail
on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    env:
      FROM_MAIL: julio.ortega@dialpad.com
      TO_MAIL: brad.paugh@dialpad.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ env.FROM_MAIL }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Dialtone updates
          to: ${{ env.TO_MAIL }}
          from: ${{ env.FROM_MAIL }}
          html_body: file://apps/dialtone-documentation/docs/about/whats-new/posts/2022-11-18.md
          bcc: ${{ env.FROM_MAIL }}
          reply_to: ${{ env.FROM_MAIL }}
          convert_markdown: true
          # Optional nodemailer log: true/false
          nodemailerlog: true
          # Optional nodemailer debug: true/false
          # if true log nodemailer will also be set true
          nodemailerdebug: true
