name: Visual Tests

on:
  push:
    branches: [ staging ]
    paths:
      - 'packages/dialtone-css/lib/build/less/**/*.less'
      - 'packages/dialtone-css/postcss/*.cjs'
      - 'packages/dialtone-css/gulpfile.cjs'
      - 'packages/dialtone-emojis/src/**'
      - 'packages/dialtone-icons/src/**'
      - 'packages/dialtone-icons/gulpfile.cjs'
      - 'packages/dialtone-tokens/*.js'
      - 'packages/dialtone-tokens/postcss/**'
      - 'packages/dialtone-tokens/themes/**'
      - 'packages/dialtone-tokens/tokens/**'
      - 'packages/dialtone-tokens/gulpfile.cjs'
      - 'packages/dialtone-vue2/**/*.vue'
      - 'packages/dialtone-vue2/**/*.stories.js'
      - 'packages/dialtone-vue2/percy.config.js'
      - '!**/*.test.*js'
  pull_request:
    types: [ unlabeled, labeled, synchronize, opened ]
    paths:
      - 'packages/dialtone-css/lib/build/less/**/*.less'
      - 'packages/dialtone-css/postcss/*.cjs'
      - 'packages/dialtone-css/gulpfile.cjs'
      - 'packages/dialtone-emojis/src/**'
      - 'packages/dialtone-icons/src/**'
      - 'packages/dialtone-icons/gulpfile.cjs'
      - 'packages/dialtone-tokens/*.js'
      - 'packages/dialtone-tokens/postcss/**'
      - 'packages/dialtone-tokens/themes/**'
      - 'packages/dialtone-tokens/tokens/**'
      - 'packages/dialtone-tokens/gulpfile.cjs'
      - 'packages/dialtone-vue2/**/*.vue'
      - 'packages/dialtone-vue2/**/*.stories.js'
      - 'packages/dialtone-vue2/percy.config.js'
      - '!**/*.test.*js'

env:
  HUSKY: 0

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  prompt-for-label:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      pull-requests: write
    steps:
      - name: Add label prompt message
        uses: mshick/add-pr-comment@v2
        if: ${{ (!contains(github.event.pull_request.labels.*.name, 'visual-test-ready') && !contains(github.event.pull_request.labels.*.name, 'no-visual-test')) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            Please add either the `visual-test-ready` or `no-visual-test` label to this PR depending on whether you want to run visual tests or not.
            It is recommended to run visual tests if your PR changes any UI. ‼️
          message-id: 'missing-visual-test-label'
          refresh-message-position: true

  dialtone-vue-2:
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'visual-test-ready')) }}
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Check out branch
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run Dialtone-vue 2 Visual Tests
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_TARGET_BRANCH: ${{ github.base_ref }}
        run: pnpm nx run --verbose dialtone-vue2:test:visual
